local CUI = CUI

local regions = {
	[1] = "us",
	[3] = "eu",
}
local realms = {
	eu = {
		[4440] = {
			names = {
				it_IT = "Everlook",
				ru_RU = "Everlook",
				en_GB = "Everlook",
				zh_TW = "永望鎮",
				ko_KR = "Everlook",
				en_US = "Everlook",
				es_MX = "Everlook",
				pt_BR = "Everlook",
				es_ES = "Everlook",
				zh_CN = "永望镇",
				fr_FR = "Everlook",
				de_DE = "Everlook",
			},
		},
		[4441] = {
			names = {
				it_IT = "Auberdine",
				ru_RU = "Auberdine",
				en_GB = "Auberdine",
				zh_TW = "奧伯丁",
				ko_KR = "Auberdine",
				en_US = "Auberdine",
				es_MX = "Auberdine",
				pt_BR = "Auberdine",
				es_ES = "Auberdine",
				zh_CN = "奥伯丁",
				fr_FR = "Auberdine",
				de_DE = "Auberdine",
			},
		},
		[4442] = {
			names = {
				it_IT = "Lakeshire",
				ru_RU = "Приозерье",
				en_GB = "Lakeshire",
				zh_TW = "湖畔鎮",
				ko_KR = "Lakeshire",
				en_US = "Lakeshire",
				es_MX = "Lakeshire",
				pt_BR = "Lakeshire",
				es_ES = "Lakeshire",
				zh_CN = "湖畔镇",
				fr_FR = "Lakeshire",
				de_DE = "Lakeshire",
			},
		},
		[4452] = {
			names = {
				it_IT = "Chromie",
				ru_RU = "Хроми",
				en_GB = "Chromie",
				zh_TW = "克羅米",
				ko_KR = "Chromie",
				en_US = "Chromie",
				es_MX = "Chromie",
				pt_BR = "Chromie",
				es_ES = "Chromie",
				zh_CN = "克罗米",
				fr_FR = "Chromie",
				de_DE = "Хроми",
			},
		},
		[4453] = {
			names = {
				it_IT = "Pyrewood Village",
				ru_RU = "Pyrewood Village",
				en_GB = "Pyrewood Village",
				zh_TW = "焚木村",
				ko_KR = "Pyrewood Village",
				en_US = "Pyrewood Village",
				es_MX = "Pyrewood Village",
				pt_BR = "Pyrewood Village",
				es_ES = "Pyrewood Village",
				zh_CN = "焚木村",
				fr_FR = "Pyrewood Village",
				de_DE = "Pyrewood Village",
			},
		},
		[4454] = {
			names = {
				it_IT = "Mirage Raceway",
				ru_RU = "Mirage Raceway",
				en_GB = "Mirage Raceway",
				zh_TW = "沙漠賽道",
				ko_KR = "Mirage Raceway",
				en_US = "Mirage Raceway",
				es_MX = "Mirage Raceway",
				pt_BR = "Mirage Raceway",
				es_ES = "Mirage Raceway",
				zh_CN = "沙漠赛道",
				fr_FR = "Mirage Raceway",
				de_DE = "Mirage Raceway",
			},
		},
		[4455] = {
			names = {
				it_IT = "Razorfen",
				ru_RU = "Razorfen",
				en_GB = "Razorfen",
				zh_TW = "剃刀高地",
				ko_KR = "Razorfen",
				en_US = "Razorfen",
				es_MX = "Razorfen",
				pt_BR = "Razorfen",
				es_ES = "Razorfen",
				zh_CN = "剃刀",
				fr_FR = "Razorfen",
				de_DE = "Razorfen",
			},
		},
		[4456] = {
			names = {
				it_IT = "Nethergarde Keep",
				ru_RU = "Nethergarde Keep",
				en_GB = "Nethergarde Keep",
				zh_TW = "守望堡",
				ko_KR = "Nethergarde Keep",
				en_US = "Nethergarde Keep",
				es_MX = "Nethergarde Keep",
				pt_BR = "Nethergarde Keep",
				es_ES = "Nethergarde Keep",
				zh_CN = "守望堡",
				fr_FR = "Nethergarde Keep",
				de_DE = "Nethergarde Keep",
			},
		},
		[4464] = {
			names = {
				it_IT = "Sulfuron",
				ru_RU = "Sulfuron",
				en_GB = "Sulfuron",
				zh_TW = "薩弗隆",
				ko_KR = "Sulfuron",
				en_US = "Sulfuron",
				es_MX = "Sulfuron",
				pt_BR = "Sulfuron",
				es_ES = "Sulfuron",
				zh_CN = "萨弗隆",
				fr_FR = "Sulfuron",
				de_DE = "Sulfuron",
			},
		},
		[4465] = {
			names = {
				it_IT = "Golemagg",
				ru_RU = "Golemagg",
				en_GB = "Golemagg",
				zh_TW = "古雷曼格",
				ko_KR = "Golemagg",
				en_US = "Golemagg",
				es_MX = "Golemagg",
				pt_BR = "Golemagg",
				es_ES = "Golemagg",
				zh_CN = "古雷曼格",
				fr_FR = "Golemagg",
				de_DE = "Golemagg",
			},
		},
		[4466] = {
			names = {
				it_IT = "Patchwerk",
				ru_RU = "Patchwerk",
				en_GB = "Patchwerk",
				zh_TW = "縫補者",
				ko_KR = "Patchwerk",
				en_US = "Patchwerk",
				es_MX = "Patchwerk",
				pt_BR = "Patchwerk",
				es_ES = "Patchwerk",
				zh_CN = "帕奇维克",
				fr_FR = "Patchwerk",
				de_DE = "Patchwerk",
			},
		},
		[4467] = {
			names = {
				it_IT = "Firemaw",
				ru_RU = "Firemaw",
				en_GB = "Firemaw",
				zh_TW = "費爾默",
				ko_KR = "Firemaw",
				en_US = "Firemaw",
				es_MX = "Firemaw",
				pt_BR = "Firemaw",
				es_ES = "Firemaw",
				zh_CN = "费尔默",
				fr_FR = "Firemaw",
				de_DE = "Firemaw",
			},
		},
		[4474] = {
			names = {
				it_IT = "Flamegor",
				ru_RU = "Пламегор",
				en_GB = "Flamegor",
				zh_TW = "弗萊格爾",
				ko_KR = "Flamegor",
				en_US = "Flamegor",
				es_MX = "Flamegor",
				pt_BR = "Flamegor",
				es_ES = "Flamegor",
				zh_CN = "弗莱格尔",
				fr_FR = "Flamegor",
				de_DE = "Пламегор",
			},
		},
		[4476] = {
			names = {
				it_IT = "Gehennas",
				ru_RU = "Gehennas",
				en_GB = "Gehennas",
				zh_TW = "基赫納斯",
				ko_KR = "Gehennas",
				en_US = "Gehennas",
				es_MX = "Gehennas",
				pt_BR = "Geena",
				es_ES = "Gehennas",
				zh_CN = "基赫纳斯",
				fr_FR = "Gehennas",
				de_DE = "Gehennas",
			},
		},
		[4477] = {
			names = {
				it_IT = "Venoxis",
				ru_RU = "Venoxis",
				en_GB = "Venoxis",
				zh_TW = "溫諾希斯",
				ko_KR = "Venoxis",
				en_US = "Venoxis",
				es_MX = "Venoxis",
				pt_BR = "Venoxis",
				es_ES = "Venoxis",
				zh_CN = "温诺希斯",
				fr_FR = "Venoxis",
				de_DE = "Venoxis",
			},
		},
		[4678] = {
			names = {
				it_IT = "Hydraxian Waterlords",
				ru_RU = "Hydraxian Waterlords",
				en_GB = "Hydraxian Waterlords",
				zh_TW = "海達希亞水元素",
				ko_KR = "Hydraxian Waterlords",
				en_US = "Hydraxian Waterlords",
				es_MX = "Hydraxian Waterlords",
				pt_BR = "Hydraxian Waterlords",
				es_ES = "Hydraxian Waterlords",
				zh_CN = "海达希亚水元素",
				fr_FR = "Hydraxian Waterlords",
				de_DE = "Hydraxian Waterlords",
			},
		},
		[4682] = {
			names = {
				it_IT = "EU4 CWOW Web",
				ru_RU = "EU4 CWOW Web",
				en_GB = "EU4 CWOW Web",
				zh_TW = "EU4 CWOW Web",
				ko_KR = "EU4 CWOW Web",
				en_US = "EU4 CWOW Web",
				es_MX = "EU4 CWOW Web",
				pt_BR = "EU4 CWOW Web",
				es_ES = "EU4 CWOW Web",
				zh_CN = "EU4 CWOW Web",
				fr_FR = "EU4 CWOW Web",
				de_DE = "EU4 CWOW Web",
			},
		},
		[4683] = {
			names = {
				it_IT = "EU5 CWOW Web",
				ru_RU = "EU5 CWOW Web",
				en_GB = "EU5 CWOW Web",
				zh_TW = "EU5 CWOW Web",
				ko_KR = "EU5 CWOW Web",
				en_US = "EU5 CWOW Web",
				es_MX = "EU5 CWOW Web",
				pt_BR = "EU5 CWOW Web",
				es_ES = "EU5 CWOW Web",
				zh_CN = "EU5 CWOW Web",
				fr_FR = "EU5 CWOW Web",
				de_DE = "EU5 CWOW Web",
			},
		},
		[4687] = {
			names = {
				it_IT = "EU4 CWOW GMSS 1",
				ru_RU = "EU4 CWOW GMSS 1",
				en_GB = "EU4 CWOW GMSS 1",
				zh_TW = "EU4 CWOW GMSS 1",
				ko_KR = "EU4 CWOW GMSS 1",
				en_US = "EU4 CWOW GMSS 1",
				es_MX = "EU4 CWOW GMSS 1",
				pt_BR = "EU4 CWOW GMSS 1",
				es_ES = "EU4 CWOW GMSS 1",
				zh_CN = "EU4 CWOW GMSS 1",
				fr_FR = "EU4 CWOW GMSS 1",
				de_DE = "EU4 CWOW GMSS 1",
			},
		},
		[4688] = {
			names = {
				it_IT = "EU4 CWOW GMSS 2",
				ru_RU = "EU4 CWOW GMSS 2",
				en_GB = "EU4 CWOW GMSS 2",
				zh_TW = "EU4 CWOW GMSS 2",
				ko_KR = "EU4 CWOW GMSS 2",
				en_US = "EU4 CWOW GMSS 2",
				es_MX = "EU4 CWOW GMSS 2",
				pt_BR = "EU4 CWOW GMSS 2",
				es_ES = "EU4 CWOW GMSS 2",
				zh_CN = "EU4 CWOW GMSS 2",
				fr_FR = "EU4 CWOW GMSS 2",
				de_DE = "EU4 CWOW GMSS 2",
			},
		},
		[4701] = {
			names = {
				it_IT = "Mograine",
				ru_RU = "Mograine",
				en_GB = "Mograine",
				zh_TW = "莫格萊尼",
				ko_KR = "Mograine",
				en_US = "Mograine",
				es_MX = "Mograine",
				pt_BR = "Mograine",
				es_ES = "Mograine",
				zh_CN = "莫格莱尼",
				fr_FR = "Mograine",
				de_DE = "Mograine",
			},
		},
		[4703] = {
			names = {
				it_IT = "Amnennar",
				ru_RU = "Amnennar",
				en_GB = "Amnennar",
				zh_TW = "亞門納爾",
				ko_KR = "Amnennar",
				en_US = "Amnennar",
				es_MX = "Amnennar",
				pt_BR = "Amnennar",
				es_ES = "Amnennar",
				zh_CN = "亚门纳尔",
				fr_FR = "Amnennar",
				de_DE = "Amnennar",
			},
		},
		[4742] = {
			names = {
				it_IT = "Ashbringer",
				ru_RU = "Испепелитель",
				en_GB = "Ashbringer",
				zh_TW = "灰燼使者",
				ko_KR = "Ashbringer",
				en_US = "Ashbringer",
				es_MX = "Ashbringer",
				pt_BR = "Ashbringer",
				es_ES = "Ashbringer",
				zh_CN = "灰烬使者",
				fr_FR = "Ashbringer",
				de_DE = "Ashbringer",
			},
		},
		[4745] = {
			names = {
				it_IT = "Transcendence",
				ru_RU = "Превосходство",
				en_GB = "Transcendence",
				zh_TW = "超凡入聖",
				ko_KR = "Transcendence",
				en_US = "Transcendence",
				es_MX = "Transcendence",
				pt_BR = "Transcendence",
				es_ES = "Transcendence",
				zh_CN = "卓越",
				fr_FR = "Transcendence",
				de_DE = "Transcendence",
			},
		},
		[4749] = {
			names = {
				it_IT = "Earthshaker",
				ru_RU = "Землекрушитель",
				en_GB = "Earthshaker",
				zh_TW = "震地者",
				ko_KR = "Earthshaker",
				en_US = "Earthshaker",
				es_MX = "Earthshaker",
				pt_BR = "Earthshaker",
				es_ES = "Earthshaker",
				zh_CN = "震地者",
				fr_FR = "Earthshaker",
				de_DE = "Earthshaker",
			},
		},
		[4811] = {
			names = {
				it_IT = "Giantstalker",
				ru_RU = "Giantstalker",
				en_GB = "Giantstalker",
				zh_TW = "巨人巡者",
				ko_KR = "Giantstalker",
				en_US = "Giantstalker",
				es_MX = "Giantstalker",
				pt_BR = "Giantstalker",
				es_ES = "Giantstalker",
				zh_CN = "巨人追猎者",
				fr_FR = "Giantstalker",
				de_DE = "Giantstalker",
			},
		},
		[4813] = {
			names = {
				it_IT = "Mandokir",
				ru_RU = "Mandokir",
				en_GB = "Mandokir",
				zh_TW = "曼多基爾",
				ko_KR = "Mandokir",
				en_US = "Mandokir",
				es_MX = "Mandokir",
				pt_BR = "Mandokir",
				es_ES = "Mandokir",
				zh_CN = "曼多基尔",
				fr_FR = "Mandokir",
				de_DE = "Mandokir",
			},
		},
		[4815] = {
			names = {
				it_IT = "Thekal",
				ru_RU = "Thekal",
				en_GB = "Thekal",
				zh_TW = "塞卡爾",
				ko_KR = "Thekal",
				en_US = "Thekal",
				es_MX = "Thekal",
				pt_BR = "Thekal",
				es_ES = "Thekal",
				zh_CN = "塞卡尔",
				fr_FR = "Thekal",
				de_DE = "Thekal",
			},
		},
		[4816] = {
			names = {
				it_IT = "Jin'do",
				ru_RU = "Jin'do",
				en_GB = "Jin'do",
				zh_TW = "金度",
				ko_KR = "Jin'do",
				en_US = "Jin'do",
				es_MX = "Jin'do",
				pt_BR = "Jin'do",
				es_ES = "Jin'do",
				zh_CN = "金度",
				fr_FR = "Jin'do",
				de_DE = "Jin'do",
			},
		},
		[6364] = {
			names = {
				it_IT = "Shek'zeer",
				ru_RU = "Shek'zeer",
				en_GB = "Shek'zeer",
				zh_TW = "杉齊爾",
				ko_KR = "셰크지르",
				en_US = "Shek'zeer",
				es_MX = "Shek'zeer",
				pt_BR = "Shek'zeer",
				es_ES = "Shek'zeer",
				zh_CN = "夏柯希尔",
				fr_FR = "Shek’zeer",
				de_DE = "Shek'zeer",
			},
		},
		[6365] = {
			names = {
				it_IT = "Garalon",
				ru_RU = "Garalon",
				en_GB = "Garalon",
				zh_TW = "加拉隆",
				ko_KR = "가랄론",
				en_US = "Garalon",
				es_MX = "Garalon",
				pt_BR = "Garalon",
				es_ES = "Garalon",
				zh_CN = "加拉隆",
				fr_FR = "Garalon",
				de_DE = "Garalon",
			},
		},
		[6366] = {
			names = {
				it_IT = "Norushen",
				ru_RU = "Norushen",
				en_GB = "Norushen",
				zh_TW = "諾努衫",
				ko_KR = "노루셴",
				en_US = "Norushen",
				es_MX = "Norushen",
				pt_BR = "Norushen",
				es_ES = "Norushen",
				zh_CN = "诺鲁什",
				fr_FR = "Norushen",
				de_DE = "Norushen",
			},
		},
		[6367] = {
			names = {
				it_IT = "Hoptallus",
				ru_RU = "Hoptallus",
				en_GB = "Hoptallus",
				zh_TW = "跳跳巨兔妖",
				ko_KR = "홉탈루스",
				en_US = "Hoptallus",
				es_MX = "Hoptallus",
				pt_BR = "Saltallus",
				es_ES = "Hoptallus",
				zh_CN = "跳跳大王",
				fr_FR = "Sautallus",
				de_DE = "Hoptallus",
			},
		},
		[6368] = {
			names = {
				it_IT = "Ook Ook",
				ru_RU = "Ook Ook",
				en_GB = "Ook Ook",
				en_US = "Ook Ook",
				es_ES = "Ook Ook",
				fr_FR = "Ook Ook",
				de_DE = "Ook Ook",
			},
		},
		[6409] = { names = { en_GB = "Thunderstrike", en_US = "Thunderstrike" } },
		[6412] = { names = { en_GB = "Spineshatter", en_US = "Spineshatter" } },
		[6418] = { names = { en_GB = "PROGWOW EU4 Web", en_US = "PROGWOW EU4 Web" } },
		[6421] = { names = { en_GB = "PROGWOW EU4 GMSS 1", en_US = "PROGWOW EU4 GMSS 1" } },
		[6540] = {
			names = {
				it_IT = "Anniversary",
				ru_RU = "Годовщина",
				en_GB = "Anniversary",
				zh_TW = "週年慶",
				ko_KR = "기념일",
				en_US = "Anniversary",
				es_MX = "Anniversary",
				pt_BR = "Aniversário",
				es_ES = "Anniversary",
				zh_CN = "周年纪念版",
				fr_FR = "Anniversary",
				de_DE = "Anniversary",
			},
		},
		[5198] = {
			names = {
				it_IT = "EU4 CWOW GMSS 2",
				ru_RU = "EU4 CWOW GMSS 2",
				en_GB = "EU4 CWOW GMSS 2",
				zh_TW = "EU4 CWOW GMSS 2",
				ko_KR = "EU4 CWOW GMSS 2",
				en_US = "EU4 CWOW GMSS 2",
				es_MX = "EU4 CWOW GMSS 2",
				pt_BR = "EU4 CWOW GMSS 2",
				es_ES = "EU4 CWOW GMSS 2",
				zh_CN = "EU4 CWOW GMSS 2",
				fr_FR = "EU4 CWOW GMSS 2",
				de_DE = "EU4 CWOW GMSS 2",
			},
		},
		[5199] = {
			names = {
				it_IT = "EU4 CWOW GMSS 1",
				ru_RU = "EU4 CWOW GMSS 1",
				en_GB = "EU4 CWOW GMSS 1",
				zh_TW = "EU4 CWOW GMSS 1",
				ko_KR = "EU4 CWOW GMSS 1",
				en_US = "EU4 CWOW GMSS 1",
				es_MX = "EU4 CWOW GMSS 1",
				pt_BR = "EU4 CWOW GMSS 1",
				es_ES = "EU4 CWOW GMSS 1",
				zh_CN = "EU4 CWOW GMSS 1",
				fr_FR = "EU4 CWOW GMSS 1",
				de_DE = "EU4 CWOW GMSS 1",
			},
		},
		[5201] = {
			names = {
				it_IT = "EU4 CWOW Web",
				ru_RU = "EU4 CWOW Web",
				en_GB = "EU4 CWOW Web",
				zh_TW = "EU4 CWOW Web",
				ko_KR = "EU4 CWOW Web",
				en_US = "EU4 CWOW Web",
				es_MX = "EU4 CWOW Web",
				pt_BR = "EU4 CWOW Web",
				es_ES = "EU4 CWOW Web",
				zh_CN = "EU4 CWOW Web",
				fr_FR = "EU4 CWOW Web",
				de_DE = "EU4 CWOW Web",
			},
		},
		[5219] = {
			names = {
				it_IT = "Dragonfang",
				ru_RU = "Dragonfang",
				en_GB = "Dragonfang",
				zh_TW = "龍牙",
				ko_KR = "Dragonfang",
				en_US = "Dragonfang",
				es_MX = "Dragonfang",
				pt_BR = "Dragonfang",
				es_ES = "Dragonfang",
				zh_CN = "龙牙",
				fr_FR = "Dragonfang",
				de_DE = "Dragonfang",
			},
		},
		[5220] = {
			names = {
				it_IT = "Stitches",
				ru_RU = "Stitches",
				en_GB = "Stitches",
				zh_TW = "縫合怪",
				ko_KR = "누더기",
				en_US = "Stitches",
				es_MX = "Stitches",
				pt_BR = "Stitches",
				es_ES = "Stitches",
				zh_CN = "缝合怪",
				fr_FR = "Stitches",
				de_DE = "Stitches",
			},
		},
		[5221] = {
			names = {
				it_IT = "Earthshaker",
				ru_RU = "Earthshaker",
				en_GB = "Earthshaker",
				zh_TW = "震地者",
				ko_KR = "Earthshaker",
				en_US = "Earthshaker",
				es_MX = "Earthshaker",
				pt_BR = "Earthshaker",
				es_ES = "Earthshaker",
				zh_CN = "震地者",
				fr_FR = "Earthshaker",
				de_DE = "Earthshaker",
			},
		},
		[5224] = {
			names = {
				it_IT = "Bloodfang",
				ru_RU = "Bloodfang",
				en_GB = "Bloodfang",
				zh_TW = "血牙",
				ko_KR = "Bloodfang",
				en_US = "Bloodfang",
				es_MX = "Bloodfang",
				pt_BR = "Bloodfang",
				es_ES = "Bloodfang",
				zh_CN = "血牙",
				fr_FR = "Bloodfang",
				de_DE = "Bloodfang",
			},
		},
		[5225] = {
			names = {
				it_IT = "Tranzendenz",
				ru_RU = "Tranzendenz",
				en_GB = "Transcendence",
				zh_TW = "超凡入聖",
				ko_KR = "Transcendence",
				en_US = "Transcendence",
				es_MX = "Transcendence",
				pt_BR = "Transcendence",
				es_ES = "Tranzendenz",
				zh_CN = "卓越",
				fr_FR = "Tranzendenz",
				de_DE = "Transcendence",
			},
		},
		[5226] = {
			names = {
				it_IT = "Finkle",
				ru_RU = "Finkle",
				en_GB = "Finkle",
				zh_TW = "芬克",
				ko_KR = "Finkle",
				en_US = "Finkle",
				es_MX = "Finkle",
				pt_BR = "Finkle",
				es_ES = "Finkle",
				zh_CN = "芬克",
				fr_FR = "Finkle",
				de_DE = "Finkle",
			},
		},
		[5227] = {
			names = {
				it_IT = "Skullflame",
				ru_RU = "Skullflame",
				en_GB = "Skullflame",
				zh_TW = "骨火",
				ko_KR = "Skullflame",
				en_US = "Skullflame",
				es_MX = "Skullflame",
				pt_BR = "Skullflame",
				es_ES = "Skullflame",
				zh_CN = "骨火",
				fr_FR = "Skullflame",
				de_DE = "Skullflame",
			},
		},
		[5228] = {
			names = {
				it_IT = "Ashbringer",
				ru_RU = "Ashbringer",
				en_GB = "Ashbringer",
				zh_TW = "灰燼使者",
				ko_KR = "Ashbringer",
				en_US = "Ashbringer",
				es_MX = "Ashbringer",
				pt_BR = "Ashbringer",
				es_ES = "Ashbringer",
				zh_CN = "灰烬使者",
				fr_FR = "Ashbringer",
				de_DE = "Ashbringer",
			},
		},
		[5229] = {
			names = {
				it_IT = "Noggenfogger",
				ru_RU = "Noggenfogger",
				en_GB = "Noggenfogger",
				zh_TW = "諾格弗格",
				ko_KR = "Noggenfogger",
				en_US = "Noggenfogger",
				es_MX = "Noggenfogger",
				pt_BR = "Noggenfogger",
				es_ES = "Noggenfogger",
				zh_CN = "诺格弗格",
				fr_FR = "Noggenfogger",
				de_DE = "Noggenfogger",
			},
		},
		[5230] = {
			names = {
				it_IT = "Gandling",
				ru_RU = "Gandling",
				en_GB = "Gandling",
				zh_TW = "加丁",
				ko_KR = "Gandling",
				en_US = "Gandling",
				es_MX = "Gandling",
				pt_BR = "Gandling",
				es_ES = "Gandling",
				zh_CN = "加丁",
				fr_FR = "Gandling",
				de_DE = "Gandling",
			},
		},
		[5231] = {
			names = {
				it_IT = "Mograine",
				ru_RU = "Mograine",
				en_GB = "Mograine",
				zh_TW = "莫格萊尼",
				ko_KR = "Mograine",
				en_US = "Mograine",
				es_MX = "Mograine",
				pt_BR = "Mograine",
				es_ES = "Mograine",
				zh_CN = "莫格莱尼",
				fr_FR = "Mograine",
				de_DE = "Mograine",
			},
		},
		[5232] = {
			names = {
				it_IT = "Zandalar Tribe",
				ru_RU = "Zandalar Tribe",
				en_GB = "Zandalar Tribe",
				zh_TW = "贊達拉部族",
				ko_KR = "Zandalar Tribe",
				en_US = "Zandalar Tribe",
				es_MX = "Zandalar Tribe",
				pt_BR = "Zandalar Tribe",
				es_ES = "Zandalar Tribe",
				zh_CN = "赞达拉部族",
				fr_FR = "Zandalar Tribe",
				de_DE = "Zandalar Tribe",
			},
		},
		[5233] = {
			names = {
				it_IT = "Firemaw",
				ru_RU = "Firemaw",
				en_GB = "Firemaw",
				zh_TW = "費爾默",
				ko_KR = "Firemaw",
				en_US = "Firemaw",
				es_MX = "Firemaw",
				pt_BR = "Firemaw",
				es_ES = "Firemaw",
				zh_CN = "费尔默",
				fr_FR = "Firemaw",
				de_DE = "Firemaw",
			},
		},
		[5234] = {
			names = {
				it_IT = "Flickwerk",
				ru_RU = "Flickwerk",
				en_GB = "Patchwerk",
				zh_TW = "縫補者",
				ko_KR = "Patchwerk",
				en_US = "Patchwerk",
				es_MX = "Patchwerk",
				pt_BR = "Patchwerk",
				es_ES = "Flickwerk",
				zh_CN = "帕奇维克",
				fr_FR = "Flickwerk",
				de_DE = "Patchwerk",
			},
		},
		[5235] = {
			names = {
				it_IT = "Golemagg",
				ru_RU = "Golemagg",
				en_GB = "Golemagg",
				zh_TW = "古雷曼格",
				ko_KR = "Golemagg",
				en_US = "Golemagg",
				es_MX = "Golemagg",
				pt_BR = "Golemagg",
				es_ES = "Golemagg",
				zh_CN = "古雷曼格",
				fr_FR = "Golemagg",
				de_DE = "Golemagg",
			},
		},
		[5236] = {
			names = {
				it_IT = "Sulfuron",
				ru_RU = "Sulfuron",
				en_GB = "Sulfuron",
				zh_TW = "薩弗隆",
				ko_KR = "Sulfuron",
				en_US = "Sulfuron",
				es_MX = "Sulfuron",
				pt_BR = "Sulfuron",
				es_ES = "Sulfuron",
				zh_CN = "萨弗隆",
				fr_FR = "Sulfuron",
				de_DE = "Sulfuron",
			},
		},
		[5237] = {
			names = {
				it_IT = "Lucifron",
				ru_RU = "Lucifron",
				en_GB = "Lucifron",
				zh_TW = "魯西弗隆",
				ko_KR = "Lucifron",
				en_US = "Lucifron",
				es_MX = "Lucifron",
				pt_BR = "Lucifron",
				es_ES = "Lucifron",
				zh_CN = "鲁西弗隆",
				fr_FR = "Lucifron",
				de_DE = "Lucifron",
			},
		},
		[5240] = {
			names = {
				it_IT = "Seenhain",
				ru_RU = "Seenhain",
				en_GB = "Lakeshire",
				zh_TW = "湖畔鎮",
				ko_KR = "Lakeshire",
				en_US = "Lakeshire",
				es_MX = "Lakeshire",
				pt_BR = "Lakeshire",
				es_ES = "Seenhain",
				zh_CN = "湖畔镇",
				fr_FR = "Seenhain",
				de_DE = "Lakeshire",
			},
		},
		[5241] = {
			names = {
				it_IT = "Auberdine",
				ru_RU = "Auberdine",
				en_GB = "Auberdine",
				zh_TW = "奧伯丁",
				ko_KR = "Auberdine",
				en_US = "Auberdine",
				es_MX = "Auberdine",
				pt_BR = "Auberdine",
				es_ES = "Auberdine",
				zh_CN = "奥伯丁",
				fr_FR = "Auberdine",
				de_DE = "Auberdine",
			},
		},
		[5242] = {
			names = {
				it_IT = "Ewige Warte",
				ru_RU = "Ewige Warte",
				en_GB = "Everlook",
				zh_TW = "永望鎮",
				ko_KR = "Everlook",
				en_US = "Everlook",
				es_MX = "Everlook",
				pt_BR = "Everlook",
				es_ES = "Ewige Warte",
				zh_CN = "永望镇",
				fr_FR = "Ewige Warte",
				de_DE = "Everlook",
			},
		},
		[5244] = {
			names = {
				it_IT = "EU5 CWOW Web",
				ru_RU = "EU5 CWOW Web",
				en_GB = "EU5 CWOW Web",
				zh_TW = "EU5 CWOW Web",
				ko_KR = "EU5 CWOW Web",
				en_US = "EU5 CWOW Web",
				es_MX = "EU5 CWOW Web",
				pt_BR = "EU5 CWOW Web",
				es_ES = "EU5 CWOW Web",
				zh_CN = "EU5 CWOW Web",
				fr_FR = "EU5 CWOW Web",
				de_DE = "EU5 CWOW Web",
			},
		},
		[5258] = {
			names = {
				it_IT = "Mandokir",
				ru_RU = "Mandokir",
				en_GB = "Mandokir",
				zh_TW = "曼多基爾",
				ko_KR = "Mandokir",
				en_US = "Mandokir",
				es_MX = "Mandokir",
				pt_BR = "Mandokir",
				es_ES = "Mandokir",
				zh_CN = "曼多基尔",
				fr_FR = "Mandokir",
				de_DE = "Mandokir",
			},
		},
		[5259] = {
			names = {
				it_IT = "Harbinger of Doom (RU)",
				ru_RU = "Вестник Рока (RU)",
				en_GB = "Harbinger of Doom (RU)",
				zh_TW = "厄運預言者(RU)",
				ko_KR = "Harbinger of Doom (RU)",
				en_US = "Harbinger of Doom (RU)",
				es_MX = "Harbinger of Doom (RU)",
				pt_BR = "Harbinger of Doom (RU)",
				es_ES = "Harbinger of Doom (RU)",
				zh_CN = "末日先驱(RU)",
				fr_FR = "Вестник Рока (RU)",
				de_DE = "Harbinger of Doom (RU)",
			},
		},
		[5261] = {
			names = {
				it_IT = "Nek'Rosh",
				ru_RU = "Nek'Rosh",
				en_GB = "Nek'Rosh",
				zh_TW = "奈克羅許",
				ko_KR = "네크로쉬",
				en_US = "Nek'Rosh",
				es_MX = "Nek'Rosh",
				pt_BR = "Nek'Rosh",
				es_ES = "Nek'Rosh",
				zh_CN = "纳克罗什",
				fr_FR = "Nek'Rosh",
				de_DE = "Nek'Rosh",
			},
		},
		[5262] = {
			names = {
				it_IT = "Herzensbrecher",
				ru_RU = "Herzensbrecher",
				en_GB = "Heartstriker",
				zh_TW = "擊心者",
				ko_KR = "Heartstriker",
				en_US = "Heartstriker",
				es_MX = "Heartstriker",
				pt_BR = "Heartstriker",
				es_ES = "Herzensbrecher",
				zh_CN = "击心者",
				fr_FR = "Herzensbrecher",
				de_DE = "Heartstriker",
			},
		},
		[5266] = {
			names = {
				it_IT = "Celebras",
				ru_RU = "Celebras",
				en_GB = "Celebras",
				zh_TW = "塞雷布拉斯",
				ko_KR = "Celebras",
				en_US = "Celebras",
				es_MX = "Celebras",
				pt_BR = "Celebras",
				es_ES = "Celebras",
				zh_CN = "塞雷布拉斯",
				fr_FR = "Celebras",
				de_DE = "Celebras",
			},
		},
		[5267] = {
			names = {
				it_IT = "Judgement",
				ru_RU = "Judgement",
				en_GB = "Judgement",
				zh_TW = "審判",
				ko_KR = "Judgement",
				en_US = "Judgement",
				es_MX = "Judgement",
				pt_BR = "Judgement",
				es_ES = "Judgement",
				zh_CN = "审判",
				fr_FR = "Judgement",
				de_DE = "Judgement",
			},
		},
		[5268] = {
			names = {
				it_IT = "Ten Storms",
				ru_RU = "Ten Storms",
				en_GB = "Ten Storms",
				zh_TW = "無盡風暴",
				ko_KR = "Ten Storms",
				en_US = "Ten Storms",
				es_MX = "Ten Storms",
				pt_BR = "Ten Storms",
				es_ES = "Ten Storms",
				zh_CN = "无尽风暴",
				fr_FR = "Ten Storms",
				de_DE = "Ten Storms",
			},
		},
		[5269] = {
			names = {
				it_IT = "Großdrachenruf",
				ru_RU = "Großdrachenruf",
				en_GB = "Dragon's Call",
				zh_TW = "龍之召喚",
				ko_KR = "Dragon's Call",
				en_US = "Dragon's Call",
				es_MX = "Dragon's Call",
				pt_BR = "Dragon's Call",
				es_ES = "Großdrachenruf",
				zh_CN = "龙之召唤",
				fr_FR = "Großdrachenruf",
				de_DE = "Dragon's Call",
			},
		},
		[5270] = {
			names = {
				it_IT = "Dreadmist",
				ru_RU = "Dreadmist",
				en_GB = "Dreadmist",
				zh_TW = "鬼霧峰",
				ko_KR = "Dreadmist",
				en_US = "Dreadmist",
				es_MX = "Dreadmist",
				pt_BR = "Dreadmist",
				es_ES = "Dreadmist",
				zh_CN = "鬼雾",
				fr_FR = "Dreadmist",
				de_DE = "Dreadmist",
			},
		},
		[5271] = {
			names = {
				it_IT = "Rhok'delar (RU)",
				ru_RU = "Рок-Делар (RU)",
				en_GB = "Rhok'delar (RU)",
				zh_TW = "洛克德拉爾(RU)",
				ko_KR = "Rhok'delar (RU)",
				en_US = "Rhok'delar (RU)",
				es_MX = "Rhok'delar (RU)",
				pt_BR = "Rhok'delar (RU)",
				es_ES = "Rhok'delar (RU)",
				zh_CN = "伦鲁迪洛尔(RU)",
				fr_FR = "Рок-Делар (RU)",
				de_DE = "Rhok'delar (RU)",
			},
		},
		[5272] = {
			names = {
				it_IT = "Flamelash",
				ru_RU = "Flamelash",
				en_GB = "Flamelash",
				zh_TW = "熾炎擊",
				ko_KR = "Flamelash",
				en_US = "Flamelash",
				es_MX = "Flamelash",
				pt_BR = "Flamelash",
				es_ES = "Flamelash",
				zh_CN = "弗莱拉斯",
				fr_FR = "Flamelash",
				de_DE = "Flamelash",
			},
		},
		[5273] = {
			names = {
				it_IT = "Stonespine",
				ru_RU = "Stonespine",
				en_GB = "Stonespine",
				zh_TW = "石脊",
				ko_KR = "Stonespine",
				en_US = "Stonespine",
				es_MX = "Stonespine",
				pt_BR = "Stonespine",
				es_ES = "Stonespine",
				zh_CN = "石脊",
				fr_FR = "Stonespine",
				de_DE = "Stonespine",
			},
		},
		[5274] = {
			names = {
				it_IT = "Wyrmthalak (RU)",
				ru_RU = "Змейталак (RU)",
				en_GB = "Wyrmthalak (RU)",
				zh_TW = "維姆薩拉克(RU)",
				ko_KR = "Wyrmthalak (RU)",
				en_US = "Wyrmthalak (RU)",
				es_MX = "Wyrmthalak (RU)",
				pt_BR = "Wyrmthalak (RU)",
				es_ES = "Wyrmthalak (RU)",
				zh_CN = "维姆萨拉克(RU)",
				fr_FR = "Змейталак (RU)",
				de_DE = "Wyrmthalak (RU)",
			},
		},
		[5275] = {
			names = {
				it_IT = "Hydraxian Waterlords",
				ru_RU = "Hydraxian Waterlords",
				en_GB = "Hydraxian Waterlords",
				zh_TW = "海達希亞水元素",
				ko_KR = "Hydraxian Waterlords",
				en_US = "Hydraxian Waterlords",
				es_MX = "Hydraxian Waterlords",
				pt_BR = "Hydraxian Waterlords",
				es_ES = "Hydraxian Waterlords",
				zh_CN = "海达希亚水元素",
				fr_FR = "Hydraxian Waterlords",
				de_DE = "Hydraxian Waterlords",
			},
		},
		[5276] = {
			names = {
				it_IT = "Razorgore",
				ru_RU = "Razorgore",
				en_GB = "Razorgore",
				zh_TW = "拉佐格爾",
				ko_KR = "Razorgore",
				en_US = "Razorgore",
				es_MX = "Razorgore",
				pt_BR = "Razorgore",
				es_ES = "Razorgore",
				zh_CN = "拉佐格尔",
				fr_FR = "Razorgore",
				de_DE = "Razorgore",
			},
		},
		[5277] = {
			names = {
				it_IT = "Venoxis",
				ru_RU = "Venoxis",
				en_GB = "Venoxis",
				zh_TW = "溫諾希斯",
				ko_KR = "Venoxis",
				en_US = "Venoxis",
				es_MX = "Venoxis",
				pt_BR = "Venoxis",
				es_ES = "Venoxis",
				zh_CN = "温诺希斯",
				fr_FR = "Venoxis",
				de_DE = "Venoxis",
			},
		},
		[5278] = {
			names = {
				it_IT = "Gehennas",
				ru_RU = "Gehennas",
				en_GB = "Gehennas",
				zh_TW = "基赫納斯",
				ko_KR = "Gehennas",
				en_US = "Gehennas",
				es_MX = "Gehennas",
				pt_BR = "Geena",
				es_ES = "Gehennas",
				zh_CN = "基赫纳斯",
				fr_FR = "Gehennas",
				de_DE = "Gehennas",
			},
		},
		[5279] = {
			names = {
				it_IT = "Shazzrah",
				ru_RU = "Shazzrah",
				en_GB = "Shazzrah",
				zh_TW = "沙斯拉爾",
				ko_KR = "Shazzrah",
				en_US = "Shazzrah",
				es_MX = "Shazzrah",
				pt_BR = "Shazzrah",
				es_ES = "Shazzrah",
				zh_CN = "沙斯拉尔",
				fr_FR = "Shazzrah",
				de_DE = "Shazzrah",
			},
		},
		[5280] = {
			names = {
				it_IT = "Flamegor (RU)",
				ru_RU = "Пламегор (RU)",
				en_GB = "Flamegor (RU)",
				zh_TW = "弗萊格爾(RU)",
				ko_KR = "Flamegor (RU)",
				en_US = "Flamegor (RU)",
				es_MX = "Flamegor (RU)",
				pt_BR = "Flamegor (RU)",
				es_ES = "Flamegor (RU)",
				zh_CN = "弗莱格尔(RU)",
				fr_FR = "Пламегор (RU)",
				de_DE = "Flamegor (RU)",
			},
		},
		[5281] = {
			names = {
				it_IT = "Nethergarde Keep",
				ru_RU = "Nethergarde Keep",
				en_GB = "Nethergarde Keep",
				zh_TW = "守望堡",
				ko_KR = "Nethergarde Keep",
				en_US = "Nethergarde Keep",
				es_MX = "Nethergarde Keep",
				pt_BR = "Nethergarde Keep",
				es_ES = "Nethergarde Keep",
				zh_CN = "守望堡",
				fr_FR = "Nethergarde Keep",
				de_DE = "Nethergarde Keep",
			},
		},
		[5282] = {
			names = {
				it_IT = "Klingenhauer",
				ru_RU = "Klingenhauer",
				en_GB = "Razorfen",
				zh_TW = "剃刀高地",
				ko_KR = "Razorfen",
				en_US = "Razorfen",
				es_MX = "Razorfen",
				pt_BR = "Razorfen",
				es_ES = "Klingenhauer",
				zh_CN = "剃刀",
				fr_FR = "Klingenhauer",
				de_DE = "Razorfen",
			},
		},
		[5283] = {
			names = {
				it_IT = "Mirage Raceway",
				ru_RU = "Mirage Raceway",
				en_GB = "Mirage Raceway",
				zh_TW = "沙漠賽道",
				ko_KR = "Mirage Raceway",
				en_US = "Mirage Raceway",
				es_MX = "Mirage Raceway",
				pt_BR = "Mirage Raceway",
				es_ES = "Mirage Raceway",
				zh_CN = "沙漠赛道",
				fr_FR = "Mirage Raceway",
				de_DE = "Mirage Raceway",
			},
		},
		[5284] = {
			names = {
				it_IT = "Pyrewood Village",
				ru_RU = "Pyrewood Village",
				en_GB = "Pyrewood Village",
				zh_TW = "焚木村",
				ko_KR = "Pyrewood Village",
				en_US = "Pyrewood Village",
				es_MX = "Pyrewood Village",
				pt_BR = "Pyrewood Village",
				es_ES = "Pyrewood Village",
				zh_CN = "焚木村",
				fr_FR = "Pyrewood Village",
				de_DE = "Pyrewood Village",
			},
		},
		[5285] = {
			names = {
				it_IT = "Chromie (RU)",
				ru_RU = "Хроми (RU)",
				en_GB = "Chromie (RU)",
				zh_TW = "克羅米(RU)",
				ko_KR = "Chromie (RU)",
				en_US = "Chromie (RU)",
				es_MX = "Chromie (RU)",
				pt_BR = "Chromie (RU)",
				es_ES = "Chromie (RU)",
				zh_CN = "克罗米(RU)",
				fr_FR = "Хроми (RU)",
				de_DE = "Chromie (RU)",
			},
		},
		[5501] = {
			names = {
				it_IT = "Amnennar",
				ru_RU = "Amnennar",
				en_GB = "Amnennar",
				zh_TW = "亞門納爾",
				ko_KR = "Amnennar",
				en_US = "Amnennar",
				es_MX = "Amnennar",
				pt_BR = "Amnennar",
				es_ES = "Amnennar",
				zh_CN = "亚门纳尔",
				fr_FR = "Amnennar",
				de_DE = "Amnennar",
			},
		},
		[5825] = {
			names = {
				it_IT = "Wild Growth",
				ru_RU = "Буйный рост",
				en_GB = "Wild Growth",
				zh_TW = "野性痊癒",
				ko_KR = "급속 성장",
				en_US = "Wild Growth",
				pt_BR = "Wild Growth",
				es_ES = "Wild Growth",
				zh_CN = "野性成长",
				fr_FR = "Wild Growth",
				de_DE = "Wild Growth",
			},
		},
		[5826] = {
			names = {
				it_IT = "Lone Wolf",
				ru_RU = "Одинокий волк",
				en_GB = "Lone Wolf",
				zh_TW = "孤狼",
				ko_KR = "고독한 늑대",
				en_US = "Lone Wolf",
				pt_BR = "Lone Wolf",
				es_ES = "Lone Wolf",
				zh_CN = "独来独往",
				fr_FR = "Lone Wolf",
				de_DE = "Lone Wolf",
			},
		},
		[5827] = {
			names = {
				it_IT = "Living Flame",
				ru_RU = "Живой жар",
				en_GB = "Living Flame",
				zh_TW = "生命烈焰",
				ko_KR = "살아있는 불꽃",
				en_US = "Living Flame",
				pt_BR = "Living Flame",
				es_ES = "Living Flame",
				zh_CN = "活化烈焰",
				fr_FR = "Living Flame",
				de_DE = "Living Flame",
			},
		},
		[5828] = {
			names = {
				it_IT = "Crusader Strike",
				ru_RU = "Удар воина Света",
				en_GB = "Crusader Strike",
				zh_TW = "十字軍聖擊",
				ko_KR = "성전사의 일격",
				en_US = "Crusader Strike",
				pt_BR = "Crusader Strike",
				es_ES = "Crusader Strike",
				zh_CN = "十字军打击",
				fr_FR = "Crusader Strike",
				de_DE = "Crusader Strike",
			},
		},
		[5829] = {
			names = {
				it_IT = "Penance (Season)",
				ru_RU = "Исповедь (сезонный)",
				en_GB = "Penance (Season)",
				zh_TW = "懺悟(賽季)",
				ko_KR = "회개 (시즌)",
				en_US = "Penance (Season)",
				es_MX = "Penance (Season)",
				pt_BR = "Penance (Season)",
				es_ES = "Penance (temporada)",
				zh_CN = "苦修（赛季）",
				fr_FR = "Penance (Season)",
				de_DE = "Penance (Saison)",
			},
		},
		[5830] = {
			names = {
				it_IT = "Shadowstrike (Season)",
				ru_RU = "Удар Тьмы (сезонный)",
				en_GB = "Shadowstrike (Season)",
				zh_TW = "暗影打擊(賽季)",
				ko_KR = "그림자 일격 (시즌)",
				en_US = "Shadowstrike (Season)",
				es_MX = "Shadowstrike (Season)",
				pt_BR = "Shadowstrike (Season)",
				es_ES = "Shadowstrike (temporada)",
				zh_CN = "暗影打击（赛季）",
				fr_FR = "Shadowstrike (Season)",
				de_DE = "Shadowstrike (Saison)",
			},
		},
		[5831] = {
			names = {
				it_IT = "Lava Lash",
				ru_RU = "Вскипание лавы",
				en_GB = "Lava Lash",
				zh_TW = "熔岩暴擊",
				ko_KR = "용암 채찍",
				en_US = "Lava Lash",
				pt_BR = "Lava Lash",
				es_ES = "Lava Lash",
				zh_CN = "熔岩猛击",
				fr_FR = "Lava Lash",
				de_DE = "Lava Lash",
			},
		},
		[5832] = {
			names = {
				it_IT = "Chaos Bolt",
				ru_RU = "Стрела Хаоса",
				en_GB = "Chaos Bolt",
				zh_TW = "混沌箭",
				ko_KR = "혼돈의 화살",
				en_US = "Chaos Bolt",
				pt_BR = "Chaos Bolt",
				es_ES = "Chaos Bolt",
				zh_CN = "混乱之箭",
				fr_FR = "Chaos Bolt",
				de_DE = "Chaos Bolt",
			},
		},
		[6111] = {
			names = {
				it_IT = "Thunderstrike",
				ru_RU = "Thunderstrike",
				en_GB = "Thunderstrike",
				zh_TW = "雷霆之擊",
				ko_KR = "천둥의 일격",
				en_US = "Thunderstrike",
				es_MX = "Thunderstrike",
				pt_BR = "Thunderstrike",
				es_ES = "Thunderstrike",
				zh_CN = "雷霆打击",
				fr_FR = "Thunderstrike",
				de_DE = "Thunderstrike",
			},
		},
		[6112] = {
			names = {
				it_IT = "Spineshatter",
				ru_RU = "Spineshatter",
				en_GB = "Spineshatter",
				zh_TW = "碎脊猛擊",
				ko_KR = "척추 파쇄",
				en_US = "Spineshatter",
				es_MX = "Spineshatter",
				pt_BR = "Spineshatter",
				es_ES = "Spineshatter",
				zh_CN = "碎脊者",
				fr_FR = "Spineshatter",
				de_DE = "Spineshatter",
			},
		},
		[6113] = {
			names = {
				it_IT = "Soulseeker",
				ru_RU = "Soulseeker",
				en_GB = "Soulseeker",
				zh_TW = "靈魂探索者",
				ko_KR = "영혼의 추적자",
				en_US = "Soulseeker",
				es_MX = "Soulseeker",
				pt_BR = "Soulseeker",
				es_ES = "Soulseeker",
				zh_CN = "搜魂者",
				fr_FR = "Soulseeker",
				de_DE = "Soulseeker",
			},
		},
		[6122] = {
			names = {
				it_IT = "Anniversary",
				ru_RU = "Годовщина",
				en_GB = "Anniversary",
				zh_TW = "週年慶",
				ko_KR = "기념일",
				en_US = "Anniversary",
				es_MX = "Anniversary",
				pt_BR = "Aniversário",
				es_ES = "Anniversary",
				zh_CN = "周年纪念版",
				fr_FR = "Anniversaire",
				de_DE = "Anniversary",
			},
		},
		[6409] = { names = { en_GB = "Thunderstrike", en_US = "Thunderstrike" } },
		[6412] = { names = { en_GB = "Spineshatter", en_US = "Spineshatter" } },
		[6418] = { names = { en_GB = "PROGWOW EU4 Web", en_US = "PROGWOW EU4 Web" } },
		[6421] = { names = { en_GB = "PROGWOW EU4 GMSS 1", en_US = "PROGWOW EU4 GMSS 1" } },
		[6540] = {
			names = {
				it_IT = "Anniversary",
				ru_RU = "Годовщина",
				en_GB = "Anniversary",
				zh_TW = "週年慶",
				ko_KR = "기념일",
				en_US = "Anniversary",
				es_MX = "Anniversary",
				pt_BR = "Aniversário",
				es_ES = "Anniversary",
				zh_CN = "周年纪念版",
				fr_FR = "Anniversary",
				de_DE = "Anniversary",
			},
		},
	},
	us = {
		[4372] = {
			names = {
				it_IT = "Atiesh",
				ru_RU = "Atiesh",
				en_GB = "Atiesh",
				zh_TW = "阿泰絲",
				ko_KR = "Atiesh",
				en_US = "Atiesh",
				es_MX = "Atiesh",
				pt_BR = "Atiesh",
				es_ES = "Atiesh",
				zh_CN = "埃提耶什",
				fr_FR = "Atiesh",
				de_DE = "Atiesh",
			},
		},
		[4373] = {
			names = {
				it_IT = "Myzrael",
				ru_RU = "Myzrael",
				en_GB = "Myzrael",
				zh_TW = "密斯賴爾",
				ko_KR = "Myzrael",
				en_US = "Myzrael",
				es_MX = "Myzrael",
				pt_BR = "Myzrael",
				es_ES = "Myzrael",
				zh_CN = "密斯莱尔",
				fr_FR = "Myzrael",
				de_DE = "Myzrael",
			},
		},
		[4374] = {
			names = {
				it_IT = "Old Blanchy",
				ru_RU = "Old Blanchy",
				en_GB = "Old Blanchy",
				zh_TW = "老馬布蘭契",
				ko_KR = "Old Blanchy",
				en_US = "Old Blanchy",
				es_MX = "Old Blanchy",
				pt_BR = "Old Blanchy",
				es_ES = "Old Blanchy",
				zh_CN = "老马布兰契",
				fr_FR = "Old Blanchy",
				de_DE = "Old Blanchy",
			},
		},
		[4376] = {
			names = {
				it_IT = "Azuresong",
				ru_RU = "Azuresong",
				en_GB = "Azuresong",
				zh_TW = "碧空之歌",
				ko_KR = "Azuresong",
				en_US = "Azuresong",
				es_MX = "Azuresong",
				pt_BR = "Azuresong",
				es_ES = "Azuresong",
				zh_CN = "碧空之歌",
				fr_FR = "Azuresong",
				de_DE = "Azuresong",
			},
		},
		[4384] = {
			names = {
				it_IT = "Mankrik",
				ru_RU = "Mankrik",
				en_GB = "Mankrik",
				zh_TW = "曼寇里克",
				ko_KR = "Mankrik",
				en_US = "Mankrik",
				es_MX = "Mankrik",
				pt_BR = "Mankrik",
				es_ES = "Mankrik",
				zh_CN = "曼科里克",
				fr_FR = "Mankrik",
				de_DE = "Mankrik",
			},
		},
		[4385] = {
			names = {
				it_IT = "Pagle",
				ru_RU = "Pagle",
				en_GB = "Pagle",
				zh_TW = "帕格",
				ko_KR = "Pagle",
				en_US = "Pagle",
				es_MX = "Pagle",
				pt_BR = "Pagle",
				es_ES = "Pagle",
				zh_CN = "帕格",
				fr_FR = "Pagle",
				de_DE = "Pagle",
			},
		},
		[4387] = {
			names = {
				it_IT = "Ashkandi",
				ru_RU = "Ashkandi",
				en_GB = "Ashkandi",
				zh_TW = "阿什坎迪",
				ko_KR = "Ashkandi",
				en_US = "Ashkandi",
				es_MX = "Ashkandi",
				pt_BR = "Ashkandi",
				es_ES = "Ashkandi",
				zh_CN = "阿什坎迪",
				fr_FR = "Ashkandi",
				de_DE = "Ashkandi",
			},
		},
		[4388] = {
			names = {
				it_IT = "Westfall",
				ru_RU = "Westfall",
				en_GB = "Westfall",
				zh_TW = "西部荒野",
				ko_KR = "Westfall",
				en_US = "Westfall",
				es_MX = "Westfall",
				pt_BR = "Westfall",
				es_ES = "Westfall",
				zh_CN = "西部荒野",
				fr_FR = "Westfall",
				de_DE = "Westfall",
			},
		},
		[4389] = {
			names = {
				it_IT = "US2 CWOW CSI 80",
				ru_RU = "US2 CWOW CSI 80",
				en_GB = "US2 CWOW CSI 80",
				zh_TW = "US2 CWOW CSI 80",
				ko_KR = "US2 CWOW CSI 80",
				en_US = "US2 CWOW CSI 80",
				es_MX = "US2 CWOW CSI 80",
				pt_BR = "US2 CWOW CSI 80",
				es_ES = "US2 CWOW CSI 80",
				zh_CN = "US2 CWOW CSI 80",
				fr_FR = "US2 CWOW CSI 80",
				de_DE = "US2 CWOW CSI 80",
			},
		},
		[4390] = {
			names = {
				it_IT = "US2 CWOW CSI 81",
				ru_RU = "US2 CWOW CSI 81",
				en_GB = "US2 CWOW CSI 81",
				zh_TW = "US2 CWOW CSI 81",
				ko_KR = "US2 CWOW CSI 81",
				en_US = "US2 CWOW CSI 81",
				es_MX = "US2 CWOW CSI 81",
				pt_BR = "US2 CWOW CSI 81",
				es_ES = "US2 CWOW CSI 81",
				zh_CN = "US2 CWOW CSI 81",
				fr_FR = "US2 CWOW CSI 81",
				de_DE = "US2 CWOW CSI 81",
			},
		},
		[4391] = {
			names = {
				it_IT = "US2 CWOW CSI 82",
				ru_RU = "US2 CWOW CSI 82",
				en_GB = "US2 CWOW CSI 82",
				zh_TW = "US2 CWOW CSI 82",
				ko_KR = "US2 CWOW CSI 82",
				en_US = "US2 CWOW CSI 82",
				es_MX = "US2 CWOW CSI 82",
				pt_BR = "US2 CWOW CSI 82",
				es_ES = "US2 CWOW CSI 82",
				zh_CN = "US2 CWOW CSI 82",
				fr_FR = "US2 CWOW CSI 82",
				de_DE = "US2 CWOW CSI 82",
			},
		},
		[4392] = {
			names = {
				it_IT = "US2 CWOW CSI 83",
				ru_RU = "US2 CWOW CSI 83",
				en_GB = "US2 CWOW CSI 83",
				zh_TW = "US2 CWOW CSI 83",
				ko_KR = "US2 CWOW CSI 83",
				en_US = "US2 CWOW CSI 83",
				es_MX = "US2 CWOW CSI 83",
				pt_BR = "US2 CWOW CSI 83",
				es_ES = "US2 CWOW CSI 83",
				zh_CN = "US2 CWOW CSI 83",
				fr_FR = "US2 CWOW CSI 83",
				de_DE = "US2 CWOW CSI 83",
			},
		},
		[4393] = {
			names = {
				it_IT = "US2 CWOW Account",
				ru_RU = "US2 CWOW Account",
				en_GB = "US2 CWOW Account",
				zh_TW = "US2 CWOW Account",
				ko_KR = "US2 CWOW Account",
				en_US = "US2 CWOW Account",
				es_MX = "US2 CWOW Account",
				pt_BR = "US2 CWOW Account",
				es_ES = "US2 CWOW Account",
				zh_CN = "US2 CWOW Account",
				fr_FR = "US2 CWOW Account",
				de_DE = "US2 CWOW Account",
			},
		},
		[4394] = {
			names = {
				it_IT = "US2 CWOW Log",
				ru_RU = "US2 CWOW Log",
				en_GB = "US2 CWOW Log",
				zh_TW = "US2 CWOW Log",
				ko_KR = "US2 CWOW Log",
				en_US = "US2 CWOW Log",
				es_MX = "US2 CWOW Log",
				pt_BR = "US2 CWOW Log",
				es_ES = "US2 CWOW Log",
				zh_CN = "US2 CWOW Log",
				fr_FR = "US2 CWOW Log",
				de_DE = "US2 CWOW Log",
			},
		},
		[4395] = {
			names = {
				it_IT = "Whitemane",
				ru_RU = "Whitemane",
				en_GB = "Whitemane",
				zh_TW = "懷特邁恩",
				ko_KR = "Whitemane",
				en_US = "Whitemane",
				es_MX = "Whitemane",
				pt_BR = "Whitemane",
				es_ES = "Whitemane",
				zh_CN = "怀特迈恩",
				fr_FR = "Whitemane",
				de_DE = "Whitemane",
			},
		},
		[4408] = {
			names = {
				it_IT = "Faerlina",
				ru_RU = "Faerlina",
				en_GB = "Faerlina",
				zh_TW = "費琳娜",
				ko_KR = "Faerlina",
				en_US = "Faerlina",
				es_MX = "Faerlina",
				pt_BR = "Faerlina",
				es_ES = "Faerlina",
				zh_CN = "法琳娜",
				fr_FR = "Faerlina",
				de_DE = "Faerlina",
			},
		},
		[4411] = {
			names = {
				it_IT = "US2 CWOW CSI 84",
				ru_RU = "US2 CWOW CSI 84",
				en_GB = "US2 CWOW CSI 84",
				zh_TW = "US2 CWOW CSI 84",
				ko_KR = "US2 CWOW CSI 84",
				en_US = "US2 CWOW CSI 84",
				es_MX = "US2 CWOW CSI 84",
				pt_BR = "US2 CWOW CSI 84",
				es_ES = "US2 CWOW CSI 84",
				zh_CN = "US2 CWOW CSI 84",
				fr_FR = "US2 CWOW CSI 84",
				de_DE = "US2 CWOW CSI 84",
			},
		},
		[4412] = {
			names = {
				it_IT = "US2 CWOW CSI 85",
				ru_RU = "US2 CWOW CSI 85",
				en_GB = "US2 CWOW CSI 85",
				zh_TW = "US2 CWOW CSI 85",
				ko_KR = "US2 CWOW CSI 85",
				en_US = "US2 CWOW CSI 85",
				es_MX = "US2 CWOW CSI 85",
				pt_BR = "US2 CWOW CSI 85",
				es_ES = "US2 CWOW CSI 85",
				zh_CN = "US2 CWOW CSI 85",
				fr_FR = "US2 CWOW CSI 85",
				de_DE = "US2 CWOW CSI 85",
			},
		},
		[4413] = {
			names = {
				it_IT = "US2 CWOW CSI 86",
				ru_RU = "US2 CWOW CSI 86",
				en_GB = "US2 CWOW CSI 86",
				zh_TW = "US2 CWOW CSI 86",
				ko_KR = "US2 CWOW CSI 86",
				en_US = "US2 CWOW CSI 86",
				es_MX = "US2 CWOW CSI 86",
				pt_BR = "US2 CWOW CSI 86",
				es_ES = "US2 CWOW CSI 86",
				zh_CN = "US2 CWOW CSI 86",
				fr_FR = "US2 CWOW CSI 86",
				de_DE = "US2 CWOW CSI 86",
			},
		},
		[4414] = {
			names = {
				it_IT = "US2 CWOW CSI 87",
				ru_RU = "US2 CWOW CSI 87",
				en_GB = "US2 CWOW CSI 87",
				zh_TW = "US2 CWOW CSI 87",
				ko_KR = "US2 CWOW CSI 87",
				en_US = "US2 CWOW CSI 87",
				es_MX = "US2 CWOW CSI 87",
				pt_BR = "US2 CWOW CSI 87",
				es_ES = "US2 CWOW CSI 87",
				zh_CN = "US2 CWOW CSI 87",
				fr_FR = "US2 CWOW CSI 87",
				de_DE = "US2 CWOW CSI 87",
			},
		},
		[4647] = {
			names = {
				it_IT = "Grobbulus",
				ru_RU = "Grobbulus",
				en_GB = "Grobbulus",
				zh_TW = "葛羅巴斯",
				ko_KR = "Grobbulus",
				en_US = "Grobbulus",
				es_MX = "Grobbulus",
				pt_BR = "Grobbulus",
				es_ES = "Grobbulus",
				zh_CN = "格罗布鲁斯",
				fr_FR = "Grobbulus",
				de_DE = "Grobbulus",
			},
		},
		[4648] = {
			names = {
				it_IT = "Bloodsail Buccaneers",
				ru_RU = "Bloodsail Buccaneers",
				en_GB = "Bloodsail Buccaneers",
				zh_TW = "血帆海盜",
				ko_KR = "Bloodsail Buccaneers",
				en_US = "Bloodsail Buccaneers",
				es_MX = "Bloodsail Buccaneers",
				pt_BR = "Bloodsail Buccaneers",
				es_ES = "Bloodsail Buccaneers",
				zh_CN = "血帆海盗",
				fr_FR = "Bloodsail Buccaneers",
				de_DE = "Bloodsail Buccaneers",
			},
		},
		[4649] = {
			names = {
				it_IT = "US1 CWOW Web",
				ru_RU = "US1 CWOW Web",
				en_GB = "US1 CWOW Web",
				zh_TW = "US1 CWOW Web",
				ko_KR = "US1 CWOW Web",
				en_US = "US1 CWOW Web",
				es_MX = "US1 CWOW Web",
				pt_BR = "US1 CWOW Web",
				es_ES = "US1 CWOW Web",
				zh_CN = "US1 CWOW Web",
				fr_FR = "US1 CWOW Web",
				de_DE = "US1 CWOW Web",
			},
		},
		[4651] = {
			names = {
				it_IT = "US2 CWOW Web",
				ru_RU = "US2 CWOW Web",
				en_GB = "US2 CWOW Web",
				zh_TW = "US2 CWOW Web",
				ko_KR = "US2 CWOW Web",
				en_US = "US2 CWOW Web",
				es_MX = "US2 CWOW Web",
				pt_BR = "US2 CWOW Web",
				es_ES = "US2 CWOW Web",
				zh_CN = "US2 CWOW Web",
				fr_FR = "US2 CWOW Web",
				de_DE = "US2 CWOW Web",
			},
		},
		[4653] = {
			names = {
				it_IT = "US1 CWOW GMSS 1",
				ru_RU = "US1 CWOW GMSS 1",
				en_GB = "US1 CWOW GMSS 1",
				zh_TW = "US1 CWOW GMSS 1",
				ko_KR = "US1 CWOW GMSS 1",
				en_US = "US1 CWOW GMSS 1",
				es_MX = "US1 CWOW GMSS 1",
				pt_BR = "US1 CWOW GMSS 1",
				es_ES = "US1 CWOW GMSS 1",
				zh_CN = "US1 CWOW GMSS 1",
				fr_FR = "US1 CWOW GMSS 1",
				de_DE = "US1 CWOW GMSS 1",
			},
		},
		[4654] = {
			names = {
				it_IT = "US1 CWOW GMSS 2",
				ru_RU = "US1 CWOW GMSS 2",
				en_GB = "US1 CWOW GMSS 2",
				zh_TW = "US1 CWOW GMSS 2",
				ko_KR = "US1 CWOW GMSS 2",
				en_US = "US1 CWOW GMSS 2",
				es_MX = "US1 CWOW GMSS 2",
				pt_BR = "US1 CWOW GMSS 2",
				es_ES = "US1 CWOW GMSS 2",
				zh_CN = "US1 CWOW GMSS 2",
				fr_FR = "US1 CWOW GMSS 2",
				de_DE = "US1 CWOW GMSS 2",
			},
		},
		[4667] = {
			names = {
				it_IT = "Remulos (AU)",
				ru_RU = "Remulos (AU)",
				en_GB = "Remulos (AU)",
				zh_TW = "雷姆洛斯（AU）",
				ko_KR = "레물로스 (AU)",
				en_US = "Remulos (AU)",
				es_MX = "Remulos (AU)",
				pt_BR = "Remulos (AU)",
				es_ES = "Remulos (AU)",
				zh_CN = "雷姆洛斯（AU）",
				fr_FR = "Remulos (AU)",
				de_DE = "Remulos (AU)",
			},
		},
		[4669] = {
			names = {
				it_IT = "Arugal (AU)",
				ru_RU = "Arugal (AU)",
				en_GB = "Arugal (AU)",
				zh_TW = "阿魯高（AU）",
				ko_KR = "아루갈 (AU)",
				en_US = "Arugal (AU)",
				es_MX = "Arugal (AU)",
				pt_BR = "Arugal (AU)",
				es_ES = "Arugal (AU)",
				zh_CN = "阿鲁高（AU）",
				fr_FR = "Arugal (AU)",
				de_DE = "Arugal (AU)",
			},
		},
		[4670] = {
			names = {
				it_IT = "Yojamba (AU)",
				ru_RU = "Yojamba (AU)",
				en_GB = "Yojamba (AU)",
				zh_TW = "尤亞姆巴（AU）",
				ko_KR = "요잠바 (AU)",
				en_US = "Yojamba (AU)",
				es_MX = "Yojamba (AU)",
				pt_BR = "Yojamba (AU)",
				es_ES = "Yojamba (AU)",
				zh_CN = "尤亚姆巴（AU）",
				fr_FR = "Yojamba (AU)",
				de_DE = "Yojamba (AU)",
			},
		},
		[4725] = {
			names = {
				it_IT = "Skyfury",
				ru_RU = "Anathema",
				en_GB = "Skyfury",
				zh_TW = "天怒",
				ko_KR = "Skyfury",
				en_US = "Skyfury",
				es_MX = "Skyfury",
				pt_BR = "Skyfury",
				es_ES = "Skyfury",
				zh_CN = "天怒",
				fr_FR = "Skyfury",
				de_DE = "Skyfury",
			},
		},
		[4726] = {
			names = {
				it_IT = "Sulfuras",
				ru_RU = "Heartseeker",
				en_GB = "Sulfuras",
				zh_TW = "薩弗拉斯",
				ko_KR = "Sulfuras",
				en_US = "Sulfuras",
				es_MX = "Sulfuras",
				pt_BR = "Sulfuras",
				es_ES = "Sulfuras",
				zh_CN = "萨弗拉斯",
				fr_FR = "Sulfuras",
				de_DE = "Sulfuras",
			},
		},
		[4727] = {
			names = {
				it_IT = "Windseeker",
				ru_RU = "Windseeker",
				en_GB = "Windseeker",
				zh_TW = "逐風者",
				ko_KR = "Windseeker",
				en_US = "Windseeker",
				es_MX = "Windseeker",
				pt_BR = "Windseeker",
				es_ES = "Windseeker",
				zh_CN = "逐风者",
				fr_FR = "Windseeker",
				de_DE = "Windseeker",
			},
		},
		[4728] = {
			names = {
				it_IT = "Benediction",
				ru_RU = "Benediction",
				en_GB = "Benediction",
				zh_TW = "祈福",
				ko_KR = "Benediction",
				en_US = "Benediction",
				es_MX = "Benediction",
				pt_BR = "Benediction",
				es_ES = "Benediction",
				zh_CN = "祈福",
				fr_FR = "Benediction",
				de_DE = "Benediction",
			},
		},
		[4731] = {
			names = {
				it_IT = "Earthfury",
				ru_RU = "Earthfury",
				en_GB = "Earthfury",
				zh_TW = "大地之怒",
				ko_KR = "Earthfury",
				en_US = "Earthfury",
				es_MX = "Earthfury",
				pt_BR = "Earthfury",
				es_ES = "Earthfury",
				zh_CN = "大地之怒",
				fr_FR = "Earthfury",
				de_DE = "Earthfury",
			},
		},
		[4738] = {
			names = {
				it_IT = "Maladath",
				ru_RU = "Nightslayer",
				en_GB = "Maladath",
				zh_TW = "瑪拉達斯",
				ko_KR = "Maladath",
				en_US = "Maladath",
				es_MX = "Maladath",
				pt_BR = "Maladath",
				es_ES = "Maladath",
				zh_CN = "玛拉达斯",
				fr_FR = "Maladath",
				de_DE = "Maladath",
			},
		},
		[4795] = {
			names = {
				it_IT = "Angerforge",
				ru_RU = "Angerforge",
				en_GB = "Angerforge",
				zh_TW = "安格弗",
				ko_KR = "Angerforge",
				en_US = "Angerforge",
				es_MX = "Angerforge",
				pt_BR = "Angerforge",
				es_ES = "Angerforge",
				zh_CN = "怒炉",
				fr_FR = "Angerforge",
				de_DE = "Angerforge",
			},
		},
		[4800] = {
			names = {
				it_IT = "Eranikus",
				ru_RU = "Eranikus",
				en_GB = "Eranikus",
				zh_TW = "伊蘭尼庫斯",
				ko_KR = "Eranikus",
				en_US = "Eranikus",
				es_MX = "Eranikus",
				pt_BR = "Eranikus",
				es_ES = "Eranikus",
				zh_CN = "伊兰尼库斯",
				fr_FR = "Eranikus",
				de_DE = "Eranikus",
			},
		},
		[5549] = { names = { en_GB = "US2 CWOW CSI 180", en_US = "US2 CWOW CSI 180" } },
		[5550] = { names = { en_GB = "US2 CWOW CSI 181", en_US = "US2 CWOW CSI 181" } },
		[5551] = { names = { en_GB = "US2 CWOW CSI 182", en_US = "US2 CWOW CSI 182" } },
		[5552] = { names = { en_GB = "US2 CWOW CSI 183", en_US = "US2 CWOW CSI 183" } },
		[5553] = { names = { en_GB = "US2 CWOW CSI 184", en_US = "US2 CWOW CSI 184" } },
		[5554] = { names = { en_GB = "US2 CWOW CSI 185", en_US = "US2 CWOW CSI 185" } },
		[5555] = { names = { en_GB = "US2 CWOW CSI 186", en_US = "US2 CWOW CSI 186" } },
		[5556] = { names = { en_GB = "US2 CWOW CSI 187", en_US = "US2 CWOW CSI 187" } },
		[6064] = { names = { en_GB = "Dreamscythe", en_US = "Dreamscythe" } },
		[6065] = { names = { en_GB = "Nightslayer", en_US = "Nightslayer" } },
		[6069] = {
			names = {
				it_IT = "PROGWOW US1 Web",
				ru_RU = "PROGWOW US1 Web",
				en_GB = "PROGWOW US1 Web",
				zh_TW = "PROGWOW US1網站",
				ko_KR = "PROGWOW US1 웹",
				en_US = "PROGWOW US1 Web",
				es_MX = "PROGWOW US1 Web",
				pt_BR = "PROGWOW US1 Web",
				es_ES = "PROGWOW US1 Web",
				zh_CN = "PROGWOW US1 Web",
				fr_FR = "PROGWOW US1 Web",
				de_DE = "PROGWOW US1 Web",
			},
		},
		[6071] = {
			names = {
				it_IT = "PROGWOW US1 GMSS 1",
				ru_RU = "PROGWOW US1 GMSS 1",
				en_GB = "PROGWOW US1 GMSS 1",
				zh_TW = "PROGWOW US1 GMSS 1",
				ko_KR = "PROGWOW US1 GMSS 1",
				en_US = "PROGWOW US1 GMSS 1",
				es_MX = "PROGWOW US1 GMSS 1",
				pt_BR = "PROGWOW US1 GMSS 1",
				es_ES = "PROGWOW US1 GMSS 1",
				zh_CN = "PROGWOW US1 GMSS 1",
				fr_FR = "PROGWOW US1 GMSS 1",
				de_DE = "PROGWOW US1 GMSS 1",
			},
		},
		[6359] = {
			names = {
				it_IT = "Nazgrim",
				ru_RU = "Nazgrim",
				en_GB = "Nazgrim",
				zh_TW = "納茲格寧姆",
				ko_KR = "나즈그림",
				en_US = "Nazgrim",
				es_MX = "Nazgrim",
				pt_BR = "Nazgrim",
				es_ES = "Nazgrim",
				zh_CN = "纳兹戈林",
				fr_FR = "Nazgrim",
				de_DE = "Nazgrim",
			},
		},
		[6360] = {
			names = {
				it_IT = "Galakras",
				ru_RU = "Galakras",
				en_GB = "Galakras",
				zh_TW = "葛拉卡斯",
				ko_KR = "갈라크라스",
				en_US = "Galakras",
				es_MX = "Galakras",
				pt_BR = "Galakras",
				es_ES = "Galakras",
				zh_CN = "迦拉卡斯",
				fr_FR = "Galakras",
				de_DE = "Galakras",
			},
		},
		[6361] = {
			names = {
				it_IT = "Ra-Den",
				ru_RU = "Ra-den",
				en_GB = "Ra-den",
				zh_TW = "萊公",
				ko_KR = "라덴",
				en_US = "Ra-den",
				es_MX = "Ra-den",
				pt_BR = "Ra-den",
				es_ES = "Ra-den",
				zh_CN = "莱登",
				fr_FR = "Ra Den",
				de_DE = "Ra-den",
			},
		},
		[6362] = {
			names = {
				it_IT = "Lei Shen",
				ru_RU = "Lei Shen",
				en_GB = "Lei Shen",
				zh_TW = "雷神",
				ko_KR = "레이 션",
				en_US = "Lei Shen",
				es_MX = "Lei Shen",
				pt_BR = "Lei Shen",
				es_ES = "Lei Shen",
				zh_CN = "雷神",
				fr_FR = "Lei Shen",
				de_DE = "Lei Shen",
			},
		},
		[6363] = {
			names = {
				it_IT = "Immerseus",
				ru_RU = "Immerseus",
				en_GB = "Immerseus",
				zh_TW = "伊莫爾西斯",
				ko_KR = "잿빛너울",
				en_US = "Immerseus",
				es_MX = "Immerseus",
				pt_BR = "Immerseus",
				es_ES = "Immerseus",
				zh_CN = "伊墨苏斯",
				fr_FR = "Immerseus",
				de_DE = "Immerseus",
			},
		},
		[6539] = { names = { en_GB = "Maladath", en_US = "Maladath" } },
		[5065] = {
			names = {
				it_IT = "Herod",
				ru_RU = "Herod",
				en_GB = "Herod",
				zh_TW = "赫洛德",
				ko_KR = "Herod",
				en_US = "Herod",
				es_MX = "Herod",
				pt_BR = "Herod",
				es_ES = "Herod",
				zh_CN = "赫洛德",
				fr_FR = "Herod",
				de_DE = "Herod",
			},
		},
		[5066] = {
			names = {
				it_IT = "Whitemane",
				ru_RU = "Whitemane",
				en_GB = "Whitemane",
				zh_TW = "懷特邁恩",
				ko_KR = "Whitemane",
				en_US = "Whitemane",
				es_MX = "Whitemane",
				pt_BR = "Whitemane",
				es_ES = "Whitemane",
				zh_CN = "怀特迈恩",
				fr_FR = "Whitemane",
				de_DE = "Whitemane",
			},
		},
		[5067] = {
			names = {
				it_IT = "Felstriker",
				ru_RU = "Felstriker",
				en_GB = "Felstriker",
				zh_TW = "惡魔之擊",
				ko_KR = "Felstriker",
				en_US = "Felstriker",
				es_MX = "Felstriker",
				pt_BR = "Felstriker",
				es_ES = "Felstriker",
				zh_CN = "恶魔之击",
				fr_FR = "Felstriker",
				de_DE = "Felstriker",
			},
		},
		[5068] = {
			names = {
				it_IT = "Westfall",
				ru_RU = "Westfall",
				en_GB = "Westfall",
				zh_TW = "西部荒野",
				ko_KR = "Westfall",
				en_US = "Westfall",
				es_MX = "Westfall",
				pt_BR = "Westfall",
				es_ES = "Westfall",
				zh_CN = "西部荒野",
				fr_FR = "Westfall",
				de_DE = "Westfall",
			},
		},
		[5069] = {
			names = {
				it_IT = "Azuresong",
				ru_RU = "Azuresong",
				en_GB = "Azuresong",
				zh_TW = "碧空之歌",
				ko_KR = "Azuresong",
				en_US = "Azuresong",
				es_MX = "Azuresong",
				pt_BR = "Azuresong",
				es_ES = "Azuresong",
				zh_CN = "碧空之歌",
				fr_FR = "Azuresong",
				de_DE = "Azuresong",
			},
		},
		[5070] = {
			names = {
				it_IT = "Yojamba",
				ru_RU = "Yojamba",
				en_GB = "Yojamba",
				zh_TW = "尤亞姆巴",
				ko_KR = "Yojamba",
				en_US = "Yojamba",
				es_MX = "Yojamba",
				pt_BR = "Yojamba",
				es_ES = "Yojamba",
				zh_CN = "尤亚姆巴",
				fr_FR = "Yojamba",
				de_DE = "Yojamba",
			},
		},
		[5071] = {
			names = {
				it_IT = "Ashkandi",
				ru_RU = "Ashkandi",
				en_GB = "Ashkandi",
				zh_TW = "阿什坎迪",
				ko_KR = "Ashkandi",
				en_US = "Ashkandi",
				es_MX = "Ashkandi",
				pt_BR = "Ashkandi",
				es_ES = "Ashkandi",
				zh_CN = "阿什坎迪",
				fr_FR = "Ashkandi",
				de_DE = "Ashkandi",
			},
		},
		[5073] = {
			names = {
				it_IT = "Arugal",
				ru_RU = "Arugal",
				en_GB = "Arugal",
				zh_TW = "阿魯高",
				ko_KR = "Arugal",
				en_US = "Arugal",
				es_MX = "Arugal",
				pt_BR = "Arugal",
				es_ES = "Arugal",
				zh_CN = "阿鲁高",
				fr_FR = "Arugal",
				de_DE = "Arugal",
			},
		},
		[5085] = {
			names = {
				it_IT = "Remulos",
				ru_RU = "Remulos",
				en_GB = "Remulos",
				zh_TW = "雷姆洛斯",
				ko_KR = "Remulos",
				en_US = "Remulos",
				es_MX = "Remulos",
				pt_BR = "Remulos",
				es_ES = "Remulos",
				zh_CN = "雷姆洛斯",
				fr_FR = "Remulos",
				de_DE = "Remulos",
			},
		},
		[5099] = {
			names = {
				it_IT = "Skull Rock",
				ru_RU = "Skull Rock",
				en_GB = "Skull Rock",
				zh_TW = "骷髏石",
				ko_KR = "해골 바위굴",
				en_US = "Skull Rock",
				es_MX = "Skull Rock",
				pt_BR = "Skull Rock",
				es_ES = "Skull Rock",
				zh_CN = "骷髅石",
				fr_FR = "Skull Rock",
				de_DE = "Skull Rock",
			},
		},
		[5100] = {
			names = {
				it_IT = "Arcanite Reaper",
				ru_RU = "Arcanite Reaper",
				en_GB = "Arcanite Reaper",
				zh_TW = "奧金收割斧",
				ko_KR = "Arcanite Reaper",
				en_US = "Arcanite Reaper",
				es_MX = "Arcanite Reaper",
				pt_BR = "Arcanite Reaper",
				es_ES = "Arcanite Reaper",
				zh_CN = "奥金斧",
				fr_FR = "Arcanite Reaper",
				de_DE = "Arcanite Reaper",
			},
		},
		[5101] = {
			names = {
				it_IT = "Anathema",
				ru_RU = "Anathema",
				en_GB = "Anathema",
				zh_TW = "咒逐",
				ko_KR = "Anathema",
				en_US = "Anathema",
				es_MX = "Anathema",
				pt_BR = "Anathema",
				es_ES = "Anathema",
				zh_CN = "咒逐",
				fr_FR = "Anathema",
				de_DE = "Anathema",
			},
		},
		[5102] = {
			names = {
				it_IT = "Thunderfury",
				ru_RU = "Thunderfury",
				en_GB = "Thunderfury",
				zh_TW = "雷霆之怒",
				ko_KR = "Thunderfury",
				en_US = "Thunderfury",
				es_MX = "Thunderfury",
				pt_BR = "Thunderfury",
				es_ES = "Thunderfury",
				zh_CN = "雷霆之怒",
				fr_FR = "Thunderfury",
				de_DE = "Thunderfury",
			},
		},
		[5105] = {
			names = {
				it_IT = "Smolderweb",
				ru_RU = "Smolderweb",
				en_GB = "Smolderweb",
				zh_TW = "煙網蛛后",
				ko_KR = "Smolderweb",
				en_US = "Smolderweb",
				es_MX = "Smolderweb",
				pt_BR = "Smolderweb",
				es_ES = "Smolderweb",
				zh_CN = "烟网",
				fr_FR = "Smolderweb",
				de_DE = "Smolderweb",
			},
		},
		[5106] = {
			names = {
				it_IT = "Rattlegore",
				ru_RU = "Rattlegore",
				en_GB = "Rattlegore",
				zh_TW = "血骨傀儡",
				ko_KR = "Rattlegore",
				en_US = "Rattlegore",
				es_MX = "Rattlegore",
				pt_BR = "Rattlegore",
				es_ES = "Rattlegore",
				zh_CN = "血骨傀儡",
				fr_FR = "Rattlegore",
				de_DE = "Rattlegore",
			},
		},
		[5107] = {
			names = {
				it_IT = "Grobbulus",
				ru_RU = "Grobbulus",
				en_GB = "Grobbulus",
				zh_TW = "葛羅巴斯",
				ko_KR = "Grobbulus",
				en_US = "Grobbulus",
				es_MX = "Grobbulus",
				pt_BR = "Grobbulus",
				es_ES = "Grobbulus",
				zh_CN = "格罗布鲁斯",
				fr_FR = "Grobbulus",
				de_DE = "Grobbulus",
			},
		},
		[5108] = {
			names = {
				it_IT = "Kurinnaxx",
				ru_RU = "Kurinnaxx",
				en_GB = "Kurinnaxx",
				zh_TW = "庫林納克斯",
				ko_KR = "Kurinnaxx",
				en_US = "Kurinnaxx",
				es_MX = "Kurinnaxx",
				pt_BR = "Kurinnaxx",
				es_ES = "Kurinnaxx",
				zh_CN = "库林纳克斯",
				fr_FR = "Kurinnaxx",
				de_DE = "Kurinnaxx",
			},
		},
		[5109] = {
			names = {
				it_IT = "Bigglesworth",
				ru_RU = "Bigglesworth",
				en_GB = "Bigglesworth",
				zh_TW = "畢勾沃斯",
				ko_KR = "Bigglesworth",
				en_US = "Bigglesworth",
				es_MX = "Bigglesworth",
				pt_BR = "Bigglesworth",
				es_ES = "Bigglesworth",
				zh_CN = "比格沃斯",
				fr_FR = "Bigglesworth",
				de_DE = "Bigglesworth",
			},
		},
		[5110] = {
			names = {
				it_IT = "Blaumeux",
				ru_RU = "Blaumeux",
				en_GB = "Blaumeux",
				zh_TW = "布洛莫斯",
				ko_KR = "Blaumeux",
				en_US = "Blaumeux",
				es_MX = "Blaumeux",
				pt_BR = "Blaumeux",
				es_ES = "Blaumeux",
				zh_CN = "布劳缪克丝",
				fr_FR = "Blaumeux",
				de_DE = "Blaumeux",
			},
		},
		[5111] = {
			names = {
				it_IT = "Fairbanks",
				ru_RU = "Fairbanks",
				en_GB = "Fairbanks",
				zh_TW = "法爾班克斯",
				ko_KR = "Fairbanks",
				en_US = "Fairbanks",
				es_MX = "Fairbanks",
				pt_BR = "Fairbanks",
				es_ES = "Fairbanks",
				zh_CN = "法尔班克斯",
				fr_FR = "Fairbanks",
				de_DE = "Fairbanks",
			},
		},
		[5115] = {
			names = {
				it_IT = "Old Blanchy",
				ru_RU = "Old Blanchy",
				en_GB = "Old Blanchy",
				zh_TW = "老馬布蘭契",
				ko_KR = "Old Blanchy",
				en_US = "Old Blanchy",
				es_MX = "Old Blanchy",
				pt_BR = "Old Blanchy",
				es_ES = "Old Blanchy",
				zh_CN = "老马布兰契",
				fr_FR = "Old Blanchy",
				de_DE = "Old Blanchy",
			},
		},
		[5116] = {
			names = {
				it_IT = "Myzrael",
				ru_RU = "Myzrael",
				en_GB = "Myzrael",
				zh_TW = "密斯賴爾",
				ko_KR = "Myzrael",
				en_US = "Myzrael",
				es_MX = "Myzrael",
				pt_BR = "Myzrael",
				es_ES = "Myzrael",
				zh_CN = "密斯莱尔",
				fr_FR = "Myzrael",
				de_DE = "Myzrael",
			},
		},
		[5117] = {
			names = {
				it_IT = "Atiesh",
				ru_RU = "Atiesh",
				en_GB = "Atiesh",
				zh_TW = "阿泰絲",
				ko_KR = "Atiesh",
				en_US = "Atiesh",
				es_MX = "Atiesh",
				pt_BR = "Atiesh",
				es_ES = "Atiesh",
				zh_CN = "埃提耶什",
				fr_FR = "Atiesh",
				de_DE = "Atiesh",
			},
		},
		[5121] = {
			names = {
				it_IT = "Loatheb",
				ru_RU = "Loatheb",
				en_GB = "Loatheb",
				zh_TW = "憎恨者",
				ko_KR = "Loatheb",
				en_US = "Loatheb",
				es_MX = "Loatheb",
				pt_BR = "Loatheb",
				es_ES = "Loatheb",
				zh_CN = "洛欧塞布",
				fr_FR = "Loatheb",
				de_DE = "Loatheb",
			},
		},
		[5124] = {
			names = {
				it_IT = "Sul'thraze",
				ru_RU = "Sul'thraze",
				en_GB = "Sul'thraze",
				zh_TW = "蘇薩斯",
				ko_KR = "Sul'thraze",
				en_US = "Sul'thraze",
				es_MX = "Sul'thraze",
				pt_BR = "Sul'thraze",
				es_ES = "Sul'thraze",
				zh_CN = "苏萨斯",
				fr_FR = "Sul'thraze",
				de_DE = "Sul'thraze",
			},
		},
		[5126] = {
			names = {
				it_IT = "Defias Pillager",
				ru_RU = "Defias Pillager",
				en_GB = "Defias Pillager",
				zh_TW = "迪菲亞掠取者",
				ko_KR = "데피아즈단 강탈자",
				en_US = "Defias Pillager",
				es_MX = "Defias Pillager",
				pt_BR = "Defias Pillager",
				es_ES = "Defias Pillager",
				zh_CN = "迪菲亚抢劫者",
				fr_FR = "Pilleur défias",
				de_DE = "Plünderer der Defias",
			},
		},
		[5129] = {
			names = {
				it_IT = "Heartseeker",
				ru_RU = "Heartseeker",
				en_GB = "Heartseeker",
				zh_TW = "尋心者",
				ko_KR = "Heartseeker",
				en_US = "Heartseeker",
				es_MX = "Heartseeker",
				pt_BR = "Heartseeker",
				es_ES = "Heartseeker",
				zh_CN = "觅心者",
				fr_FR = "Heartseeker",
				de_DE = "Heartseeker",
			},
		},
		[5130] = {
			names = {
				it_IT = "Earthfury",
				ru_RU = "Earthfury",
				en_GB = "Earthfury",
				zh_TW = "大地震怒",
				ko_KR = "Earthfury",
				en_US = "Earthfury",
				es_MX = "Earthfury",
				pt_BR = "Earthfury",
				es_ES = "Earthfury",
				zh_CN = "大地之怒",
				fr_FR = "Earthfury",
				de_DE = "Earthfury",
			},
		},
		[5132] = {
			names = {
				it_IT = "Netherwind",
				ru_RU = "Netherwind",
				en_GB = "Netherwind",
				zh_TW = "靈風",
				ko_KR = "Netherwind",
				en_US = "Netherwind",
				es_MX = "Netherwind",
				pt_BR = "Netherwind",
				es_ES = "Netherwind",
				zh_CN = "灵风",
				fr_FR = "Netherwind",
				de_DE = "Netherwind",
			},
		},
		[5133] = {
			names = {
				it_IT = "Benediction",
				ru_RU = "Benediction",
				en_GB = "Benediction",
				zh_TW = "祈福",
				ko_KR = "Benediction",
				en_US = "Benediction",
				es_MX = "Benediction",
				pt_BR = "Benediction",
				es_ES = "Benediction",
				zh_CN = "祈福",
				fr_FR = "Benediction",
				de_DE = "Benediction",
			},
		},
		[5134] = {
			names = {
				it_IT = "Windseeker",
				ru_RU = "Windseeker",
				en_GB = "Windseeker",
				zh_TW = "逐風者",
				ko_KR = "Windseeker",
				en_US = "Windseeker",
				es_MX = "Windseeker",
				pt_BR = "Windseeker",
				es_ES = "Windseeker",
				zh_CN = "逐风者",
				fr_FR = "Windseeker",
				de_DE = "Windseeker",
			},
		},
		[5135] = {
			names = {
				it_IT = "Sulfuras",
				ru_RU = "Sulfuras",
				en_GB = "Sulfuras",
				zh_TW = "薩弗拉斯",
				ko_KR = "Sulfuras",
				en_US = "Sulfuras",
				es_MX = "Sulfuras",
				pt_BR = "Sulfuras",
				es_ES = "Sulfuras",
				zh_CN = "萨弗拉斯",
				fr_FR = "Sulfuras",
				de_DE = "Sulfuras",
			},
		},
		[5136] = {
			names = {
				it_IT = "Kirtonos",
				ru_RU = "Kirtonos",
				en_GB = "Kirtonos",
				zh_TW = "基爾圖諾斯",
				ko_KR = "Kirtonos",
				en_US = "Kirtonos",
				es_MX = "Kirtonos",
				pt_BR = "Kirtonos",
				es_ES = "Kirtonos",
				zh_CN = "基尔图诺斯",
				fr_FR = "Kirtonos",
				de_DE = "Kirtonos",
			},
		},
		[5137] = {
			names = {
				it_IT = "Kromcrush",
				ru_RU = "Kromcrush",
				en_GB = "Kromcrush",
				zh_TW = "克羅卡斯",
				ko_KR = "Kromcrush",
				en_US = "Kromcrush",
				es_MX = "Kromcrush",
				pt_BR = "Kromcrush",
				es_ES = "Kromcrush",
				zh_CN = "克罗卡斯",
				fr_FR = "Kromcrush",
				de_DE = "Kromcrush",
			},
		},
		[5138] = {
			names = {
				it_IT = "Incendius",
				ru_RU = "Incendius",
				en_GB = "Incendius",
				zh_TW = "伊森迪奧斯",
				ko_KR = "Incendius",
				en_US = "Incendius",
				es_MX = "Incendius",
				pt_BR = "Incendius",
				es_ES = "Incendius",
				zh_CN = "伊森迪奥斯",
				fr_FR = "Incendius",
				de_DE = "Incendius",
			},
		},
		[5139] = {
			names = {
				it_IT = "Bloodsail Buccaneers",
				ru_RU = "Bloodsail Buccaneers",
				en_GB = "Bloodsail Buccaneers",
				zh_TW = "血帆海盜",
				ko_KR = "Bloodsail Buccaneers",
				en_US = "Bloodsail Buccaneers",
				es_MX = "Bloodsail Buccaneers",
				pt_BR = "Bloodsail Buccaneers",
				es_ES = "Bloodsail Buccaneers",
				zh_CN = "血帆海盗",
				fr_FR = "Bloodsail Buccaneers",
				de_DE = "Bloodsail Buccaneers",
			},
		},
		[5140] = {
			names = {
				it_IT = "Skeram",
				ru_RU = "Skeram",
				en_GB = "Skeram",
				zh_TW = "斯克拉姆",
				ko_KR = "Skeram",
				en_US = "Skeram",
				es_MX = "Skeram",
				pt_BR = "Skeram",
				es_ES = "Skeram",
				zh_CN = "斯克拉姆",
				fr_FR = "Skeram",
				de_DE = "Skeram",
			},
		},
		[5141] = {
			names = {
				it_IT = "Stalagg",
				ru_RU = "Stalagg",
				en_GB = "Stalagg",
				zh_TW = "斯塔拉格",
				ko_KR = "Stalagg",
				en_US = "Stalagg",
				es_MX = "Stalagg",
				pt_BR = "Stalagg",
				es_ES = "Stalagg",
				zh_CN = "斯塔拉格",
				fr_FR = "Stalagg",
				de_DE = "Stalagg",
			},
		},
		[5142] = {
			names = {
				it_IT = "Faerlina",
				ru_RU = "Faerlina",
				en_GB = "Faerlina",
				zh_TW = "費琳娜",
				ko_KR = "Faerlina",
				en_US = "Faerlina",
				es_MX = "Faerlina",
				pt_BR = "Faerlina",
				es_ES = "Faerlina",
				zh_CN = "法琳娜",
				fr_FR = "Faerlina",
				de_DE = "Faerlina",
			},
		},
		[5143] = {
			names = {
				it_IT = "Thalnos",
				ru_RU = "Thalnos",
				en_GB = "Thalnos",
				zh_TW = "薩爾諾斯",
				ko_KR = "Thalnos",
				en_US = "Thalnos",
				es_MX = "Thalnos",
				pt_BR = "Thalnos",
				es_ES = "Thalnos",
				zh_CN = "萨尔诺斯",
				fr_FR = "Thalnos",
				de_DE = "Thalnos",
			},
		},
		[5147] = {
			names = {
				it_IT = "Deviate Delight",
				ru_RU = "Deviate Delight",
				en_GB = "Deviate Delight",
				zh_TW = "變異點心",
				ko_KR = "Deviate Delight",
				en_US = "Deviate Delight",
				es_MX = "Deviate Delight",
				pt_BR = "Deviate Delight",
				es_ES = "Deviate Delight",
				zh_CN = "美味风蛇",
				fr_FR = "Deviate Delight",
				de_DE = "Deviate Delight",
			},
		},
		[5148] = {
			names = {
				it_IT = "Pagle",
				ru_RU = "Pagle",
				en_GB = "Pagle",
				zh_TW = "帕格",
				ko_KR = "Pagle",
				en_US = "Pagle",
				es_MX = "Pagle",
				pt_BR = "Pagle",
				es_ES = "Pagle",
				zh_CN = "帕格",
				fr_FR = "Pagle",
				de_DE = "Pagle",
			},
		},
		[5149] = {
			names = {
				it_IT = "Mankrik",
				ru_RU = "Mankrik",
				en_GB = "Mankrik",
				zh_TW = "曼寇里克",
				ko_KR = "Mankrik",
				en_US = "Mankrik",
				es_MX = "Mankrik",
				pt_BR = "Mankrik",
				es_ES = "Mankrik",
				zh_CN = "曼科里克",
				fr_FR = "Mankrik",
				de_DE = "Mankrik",
			},
		},
		[5155] = {
			names = {
				it_IT = "US2 VANWOW Log",
				ru_RU = "US2 VANWOW Log",
				en_GB = "US2 VANWOW Log",
				zh_TW = "US2 VANWOW Log",
				ko_KR = "US2 VANWOW 기록",
				en_US = "US2 VANWOW Log",
				es_MX = "US2 VANWOW Log",
				pt_BR = "US2 VANWOW Log",
				es_ES = "US2 VANWOW Log",
				zh_CN = "US2 VANWOW Log",
				fr_FR = "US2 VANWOW Log",
				de_DE = "US2 VANWOW Log",
			},
		},
		[5156] = {
			names = {
				it_IT = "US2 VANWOW Web",
				ru_RU = "US2 VANWOW Web",
				en_GB = "US2 VANWOW Web",
				zh_TW = "US2 VANWOW Web",
				ko_KR = "US2 VANWOW 웹",
				en_US = "US2 VANWOW Web",
				es_MX = "US2 VANWOW Web",
				pt_BR = "US2 VANWOW Web",
				es_ES = "US2 VANWOW Web",
				zh_CN = "US2 VANWOW Web",
				fr_FR = "US2 VANWOW Web",
				de_DE = "US2 VANWOW Web",
			},
		},
		[5157] = {
			names = {
				it_IT = "US2 VANWOW Account",
				ru_RU = "US2 VANWOW Account",
				en_GB = "US2 VANWOW Account",
				zh_TW = "US2 VANWOW Account",
				ko_KR = "US2 VANWOW 계정",
				en_US = "US2 VANWOW Account",
				es_MX = "US2 VANWOW Account",
				pt_BR = "US2 VANWOW Account",
				es_ES = "US2 VANWOW Account",
				zh_CN = "US2 VANWOW Account",
				fr_FR = "US2 VANWOW Account",
				de_DE = "US2 VANWOW Account",
			},
		},
		[5158] = {
			names = {
				it_IT = "US2 VANWOW CSI 87",
				ru_RU = "US2 VANWOW CSI 87",
				en_GB = "US2 VANWOW CSI 87",
				zh_TW = "US2 VANWOW CSI 87",
				ko_KR = "US2 VANWOW CSI 87",
				en_US = "US2 VANWOW CSI 87",
				es_MX = "US2 VANWOW CSI 87",
				pt_BR = "US2 VANWOW CSI 87",
				es_ES = "US2 VANWOW CSI 87",
				zh_CN = "US2 VANWOW CSI 87",
				fr_FR = "US2 VANWOW CSI 87",
				de_DE = "US2 VANWOW CSI 87",
			},
		},
		[5159] = {
			names = {
				it_IT = "US2 VANWOW CSI 86",
				ru_RU = "US2 VANWOW CSI 86",
				en_GB = "US2 VANWOW CSI 86",
				zh_TW = "US2 VANWOW CSI 86",
				ko_KR = "US2 VANWOW CSI 86",
				en_US = "US2 VANWOW CSI 86",
				es_MX = "US2 VANWOW CSI 86",
				pt_BR = "US2 VANWOW CSI 86",
				es_ES = "US2 VANWOW CSI 86",
				zh_CN = "US2 VANWOW CSI 86",
				fr_FR = "US2 VANWOW CSI 86",
				de_DE = "US2 VANWOW CSI 86",
			},
		},
		[5160] = {
			names = {
				it_IT = "US2 VANWOW CSI 85",
				ru_RU = "US2 VANWOW CSI 85",
				en_GB = "US2 VANWOW CSI 85",
				zh_TW = "US2 VANWOW CSI 85",
				ko_KR = "US2 VANWOW CSI 85",
				en_US = "US2 VANWOW CSI 85",
				es_MX = "US2 VANWOW CSI 85",
				pt_BR = "US2 VANWOW CSI 85",
				es_ES = "US2 VANWOW CSI 85",
				zh_CN = "US2 VANWOW CSI 85",
				fr_FR = "US2 VANWOW CSI 85",
				de_DE = "US2 VANWOW CSI 85",
			},
		},
		[5161] = {
			names = {
				it_IT = "US2 VANWOW CSI 84",
				ru_RU = "US2 VANWOW CSI 84",
				en_GB = "US2 VANWOW CSI 84",
				zh_TW = "US2 VANWOW CSI 84",
				ko_KR = "US2 VANWOW CSI 84",
				en_US = "US2 VANWOW CSI 84",
				es_MX = "US2 VANWOW CSI 84",
				pt_BR = "US2 VANWOW CSI 84",
				es_ES = "US2 VANWOW CSI 84",
				zh_CN = "US2 VANWOW CSI 84",
				fr_FR = "US2 VANWOW CSI 84",
				de_DE = "US2 VANWOW CSI 84",
			},
		},
		[5162] = {
			names = {
				it_IT = "US2 VANWOW CSI 83",
				ru_RU = "US2 VANWOW CSI 83",
				en_GB = "US2 VANWOW CSI 83",
				zh_TW = "US2 VANWOW CSI 83",
				ko_KR = "US2 VANWOW CSI 83",
				en_US = "US2 VANWOW CSI 83",
				es_MX = "US2 VANWOW CSI 83",
				pt_BR = "US2 VANWOW CSI 83",
				es_ES = "US2 VANWOW CSI 83",
				zh_CN = "US2 VANWOW CSI 83",
				fr_FR = "US2 VANWOW CSI 83",
				de_DE = "US2 VANWOW CSI 83",
			},
		},
		[5163] = {
			names = {
				it_IT = "US2 VANWOW CSI 82",
				ru_RU = "US2 VANWOW CSI 82",
				en_GB = "US2 VANWOW CSI 82",
				zh_TW = "US2 VANWOW CSI 82",
				ko_KR = "US2 VANWOW CSI 82",
				en_US = "US2 VANWOW CSI 82",
				es_MX = "US2 VANWOW CSI 82",
				pt_BR = "US2 VANWOW CSI 82",
				es_ES = "US2 VANWOW CSI 82",
				zh_CN = "US2 VANWOW CSI 82",
				fr_FR = "US2 VANWOW CSI 82",
				de_DE = "US2 VANWOW CSI 82",
			},
		},
		[5164] = {
			names = {
				it_IT = "US2 VANWOW CSI 81",
				ru_RU = "US2 VANWOW CSI 81",
				en_GB = "US2 VANWOW CSI 81",
				zh_TW = "US2 VANWOW CSI 81",
				ko_KR = "US2 VANWOW CSI 81",
				en_US = "US2 VANWOW CSI 81",
				es_MX = "US2 VANWOW CSI 81",
				pt_BR = "US2 VANWOW CSI 81",
				es_ES = "US2 VANWOW CSI 81",
				zh_CN = "US2 VANWOW CSI 81",
				fr_FR = "US2 VANWOW CSI 81",
				de_DE = "US2 VANWOW CSI 81",
			},
		},
		[5165] = {
			names = {
				it_IT = "US2 VANWOW CSI 80",
				ru_RU = "US2 VANWOW CSI 80",
				en_GB = "US2 VANWOW CSI 80",
				zh_TW = "US2 VANWOW CSI 80",
				ko_KR = "US2 VANWOW CSI 80",
				en_US = "US2 VANWOW CSI 80",
				es_MX = "US2 VANWOW CSI 80",
				pt_BR = "US2 VANWOW CSI 80",
				es_ES = "US2 VANWOW CSI 80",
				zh_CN = "US2 VANWOW CSI 80",
				fr_FR = "US2 VANWOW CSI 80",
				de_DE = "US2 VANWOW CSI 80",
			},
		},
		[5166] = {
			names = {
				it_IT = "US1 VANWOW GMSS 1",
				ru_RU = "US1 VANWOW GMSS 1",
				en_GB = "US1 VANWOW GMSS 1",
				zh_TW = "US1 VANWOW GMSS 1",
				ko_KR = "US1 VANWOW GMSS 1",
				en_US = "US1 VANWOW GMSS 1",
				es_MX = "US1 VANWOW GMSS 1",
				pt_BR = "US1 VANWOW GMSS 1",
				es_ES = "US1 VANWOW GMSS 1",
				zh_CN = "US1 VANWOW GMSS 1",
				fr_FR = "US1 VANWOW GMSS 1",
				de_DE = "US1 VANWOW GMSS 1",
			},
		},
		[5168] = {
			names = {
				it_IT = "US1 VANWOW Web",
				ru_RU = "US1 VANWOW Web",
				en_GB = "US1 VANWOW Web",
				zh_TW = "US1 VANWOW Web",
				ko_KR = "US1 VANWOW 웹",
				en_US = "US1 VANWOW Web",
				es_MX = "US1 VANWOW Web",
				pt_BR = "US1 VANWOW Web",
				es_ES = "US1 VANWOW Web",
				zh_CN = "US1 VANWOW Web",
				fr_FR = "US1 VANWOW Web",
				de_DE = "US1 VANWOW Web",
			},
		},
		[5180] = {
			names = {
				it_IT = "US1 VANWOW GMSS 2",
				ru_RU = "US1 VANWOW GMSS 2",
				en_GB = "US1 VANWOW GMSS 2",
				zh_TW = "US1 VANWOW GMSS 2",
				ko_KR = "US1 VANWOW GMSS 2",
				en_US = "US1 VANWOW GMSS 2",
				es_MX = "US1 VANWOW GMSS 2",
				pt_BR = "US1 VANWOW GMSS 2",
				es_ES = "US1 VANWOW GMSS 2",
				zh_CN = "US1 VANWOW GMSS 2",
				fr_FR = "US1 VANWOW GMSS 2",
				de_DE = "US1 VANWOW GMSS 2",
			},
		},
		[5813] = {
			names = {
				it_IT = "Wild Growth",
				ru_RU = "Буйный рост",
				en_GB = "Wild Growth",
				zh_TW = "野性痊癒",
				ko_KR = "급속 성장",
				en_US = "Wild Growth",
				pt_BR = "Wild Growth",
				es_ES = "Wild Growth",
				zh_CN = "野性成长",
				fr_FR = "Wild Growth",
				de_DE = "Wild Growth",
			},
		},
		[5814] = {
			names = {
				it_IT = "Lone Wolf",
				ru_RU = "Одинокий волк",
				en_GB = "Lone Wolf",
				zh_TW = "孤狼",
				ko_KR = "고독한 늑대",
				en_US = "Lone Wolf",
				pt_BR = "Lone Wolf",
				es_ES = "Lone Wolf",
				zh_CN = "独来独往",
				fr_FR = "Lone Wolf",
				de_DE = "Lone Wolf",
			},
		},
		[5815] = {
			names = {
				it_IT = "Living Flame",
				ru_RU = "Живой жар",
				en_GB = "Living Flame",
				zh_TW = "生命烈焰",
				ko_KR = "살아있는 불꽃",
				en_US = "Living Flame",
				pt_BR = "Living Flame",
				es_ES = "Living Flame",
				zh_CN = "活化烈焰",
				fr_FR = "Living Flame",
				de_DE = "Living Flame",
			},
		},
		[5816] = {
			names = {
				it_IT = "Crusader Strike",
				ru_RU = "Удар воина Света",
				en_GB = "Crusader Strike",
				zh_TW = "十字軍聖擊",
				ko_KR = "성전사의 일격",
				en_US = "Crusader Strike",
				pt_BR = "Crusader Strike",
				es_ES = "Crusader Strike",
				zh_CN = "十字军打击",
				fr_FR = "Crusader Strike",
				de_DE = "Crusader Strike",
			},
		},
		[5817] = {
			names = {
				it_IT = "Penance (AU)",
				ru_RU = "Penance (AU)",
				en_GB = "Penance (AU)",
				zh_TW = "懺悟(AU)",
				ko_KR = "회개 (AU)",
				en_US = "Penance (AU)",
				es_MX = "Penance (AU)",
				pt_BR = "Penance (AU)",
				es_ES = "Penance (AU)",
				zh_CN = "苦修（澳洲）",
				fr_FR = "Penance (AU)",
				de_DE = "Penance (AU)",
			},
		},
		[5818] = {
			names = {
				it_IT = "Shadowstrike (AU)",
				ru_RU = "Shadowstrike (AU)",
				en_GB = "Shadowstrike (AU)",
				zh_TW = "暗影打擊(AU)",
				ko_KR = "그림자 일격 (AU)",
				en_US = "Shadowstrike (AU)",
				es_MX = "Shadowstrike (AU)",
				pt_BR = "Shadowstrike (AU)",
				es_ES = "Shadowstrike (AU)",
				zh_CN = "暗影打击（澳洲）",
				fr_FR = "Shadowstrike (AU)",
				de_DE = "Shadowstrike (AU)",
			},
		},
		[5819] = {
			names = {
				it_IT = "Lava Lash",
				ru_RU = "Вскипание лавы",
				en_GB = "Lava Lash",
				zh_TW = "熔岩暴擊",
				ko_KR = "용암 채찍",
				en_US = "Lava Lash",
				pt_BR = "Lava Lash",
				es_ES = "Lava Lash",
				zh_CN = "熔岩猛击",
				fr_FR = "Lava Lash",
				de_DE = "Lava Lash",
			},
		},
		[5820] = {
			names = {
				it_IT = "Chaos Bolt",
				ru_RU = "Стрела Хаоса",
				en_GB = "Chaos Bolt",
				zh_TW = "混沌箭",
				ko_KR = "혼돈의 화살",
				en_US = "Chaos Bolt",
				pt_BR = "Chaos Bolt",
				es_ES = "Chaos Bolt",
				zh_CN = "混乱之箭",
				fr_FR = "Chaos Bolt",
				de_DE = "Chaos Bolt",
			},
		},
		[6103] = {
			names = {
				it_IT = "Dreamscythe",
				ru_RU = "Dreamscythe",
				en_GB = "Dreamscythe",
				zh_TW = "德姆塞卡爾",
				ko_KR = "드림사이드",
				en_US = "Dreamscythe",
				es_MX = "Dreamscythe",
				pt_BR = "Dreamscythe",
				es_ES = "Dreamscythe",
				zh_CN = "德姆塞卡尔",
				fr_FR = "Dreamscythe",
				de_DE = "Dreamscythe",
			},
		},
		[6104] = {
			names = {
				it_IT = "Nightslayer",
				ru_RU = "Nightslayer",
				en_GB = "Nightslayer",
				zh_TW = "黑夜殺手",
				ko_KR = "밤그림자",
				en_US = "Nightslayer",
				es_MX = "Nightslayer",
				pt_BR = "Nightslayer",
				es_ES = "Nightslayer",
				zh_CN = "夜幕杀手",
				fr_FR = "Nightslayer",
				de_DE = "Nightslayer",
			},
		},
		[6105] = {
			names = {
				it_IT = "Doomhowl",
				ru_RU = "Doomhowl",
				en_GB = "Doomhowl",
				zh_TW = "末日哀嚎",
				ko_KR = "파멸의 포효",
				en_US = "Doomhowl",
				es_MX = "Doomhowl",
				pt_BR = "Doomhowl",
				es_ES = "Doomhowl",
				zh_CN = "末日之吼",
				fr_FR = "Doomhowl",
				de_DE = "Doomhowl",
			},
		},
		[6131] = {
			names = {
				it_IT = "Maladath (AU)",
				ru_RU = "Maladath (AU)",
				en_GB = "Maladath (AU)",
				zh_TW = "瑪拉達斯(AU)",
				ko_KR = "말라다스 (AU)",
				en_US = "Maladath (AU)",
				es_MX = "Maladath (AU)",
				pt_BR = "Maladath (AU)",
				es_ES = "Maladath (AU)",
				zh_CN = "玛拉达斯（AU）",
				fr_FR = "Maladath (AU)",
				de_DE = "Maladath (AU)",
			},
		},
		[6064] = { names = { en_GB = "Dreamscythe", en_US = "Dreamscythe" } },
		[6065] = { names = { en_GB = "Nightslayer", en_US = "Nightslayer" } },
		[6069] = {
			names = {
				it_IT = "PROGWOW US1 Web",
				ru_RU = "PROGWOW US1 Web",
				en_GB = "PROGWOW US1 Web",
				zh_TW = "PROGWOW US1網站",
				ko_KR = "PROGWOW US1 웹",
				en_US = "PROGWOW US1 Web",
				es_MX = "PROGWOW US1 Web",
				pt_BR = "PROGWOW US1 Web",
				es_ES = "PROGWOW US1 Web",
				zh_CN = "PROGWOW US1 Web",
				fr_FR = "PROGWOW US1 Web",
				de_DE = "PROGWOW US1 Web",
			},
		},
		[6071] = {
			names = {
				it_IT = "PROGWOW US1 GMSS 1",
				ru_RU = "PROGWOW US1 GMSS 1",
				en_GB = "PROGWOW US1 GMSS 1",
				zh_TW = "PROGWOW US1 GMSS 1",
				ko_KR = "PROGWOW US1 GMSS 1",
				en_US = "PROGWOW US1 GMSS 1",
				es_MX = "PROGWOW US1 GMSS 1",
				pt_BR = "PROGWOW US1 GMSS 1",
				es_ES = "PROGWOW US1 GMSS 1",
				zh_CN = "PROGWOW US1 GMSS 1",
				fr_FR = "PROGWOW US1 GMSS 1",
				de_DE = "PROGWOW US1 GMSS 1",
			},
		},
		[6539] = { names = { en_GB = "Maladath", en_US = "Maladath" } },
	},
}

function CUI:GetRealmName(gameAccountInfo, locale)
	if locale == nil then
		locale = "en_GB"
	end
	local realmID = gameAccountInfo.realmID
	local region = regions[gameAccountInfo.regionID]
	local realmInfo = realms[region][realmID]
	if realmInfo and realmInfo.names then
		return realmInfo.names[locale]
	end

	self:Print("realmid: " .. realmID)
	self:Print("region: " .. region)
	self:Print("locale: " .. locale)
	DevTools_Dump(realmInfo)
	return "Unknown"
end
